// Code generated by ent, DO NOT EDIT.

package evaluationcase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the evaluationcase type in the database.
	Label = "evaluation_case"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDatasetVersionID holds the string denoting the dataset_version_id field in the database.
	FieldDatasetVersionID = "dataset_version_id"
	// FieldCaseKey holds the string denoting the case_key field in the database.
	FieldCaseKey = "case_key"
	// FieldCapabilityDomain holds the string denoting the capability_domain field in the database.
	FieldCapabilityDomain = "capability_domain"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldSampleCount holds the string denoting the sample_count field in the database.
	FieldSampleCount = "sample_count"
	// FieldPromptSpec holds the string denoting the prompt_spec field in the database.
	FieldPromptSpec = "prompt_spec"
	// FieldExpectedSpec holds the string denoting the expected_spec field in the database.
	FieldExpectedSpec = "expected_spec"
	// FieldEncryptedSpec holds the string denoting the encrypted_spec field in the database.
	FieldEncryptedSpec = "encrypted_spec"
	// FieldExecutionSpec holds the string denoting the execution_spec field in the database.
	FieldExecutionSpec = "execution_spec"
	// FieldQualityDimension holds the string denoting the quality_dimension field in the database.
	FieldQualityDimension = "quality_dimension"
	// FieldQualityProbeSpec holds the string denoting the quality_probe_spec field in the database.
	FieldQualityProbeSpec = "quality_probe_spec"
	// FieldGraderID holds the string denoting the grader_id field in the database.
	FieldGraderID = "grader_id"
	// FieldGraderVersion holds the string denoting the grader_version field in the database.
	FieldGraderVersion = "grader_version"
	// FieldContentSha256 holds the string denoting the content_sha256 field in the database.
	FieldContentSha256 = "content_sha256"
	// FieldConfidentiality holds the string denoting the confidentiality field in the database.
	FieldConfidentiality = "confidentiality"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDatasetVersion holds the string denoting the dataset_version edge name in mutations.
	EdgeDatasetVersion = "dataset_version"
	// Table holds the table name of the evaluationcase in the database.
	Table = "evaluation_cases"
	// DatasetVersionTable is the table that holds the dataset_version relation/edge.
	DatasetVersionTable = "evaluation_cases"
	// DatasetVersionInverseTable is the table name for the EvaluationDatasetVersion entity.
	// It exists in this package in order to avoid circular dependency with the "evaluationdatasetversion" package.
	DatasetVersionInverseTable = "evaluation_dataset_versions"
	// DatasetVersionColumn is the table column denoting the dataset_version relation/edge.
	DatasetVersionColumn = "dataset_version_id"
)

// Columns holds all SQL columns for evaluationcase fields.
var Columns = []string{
	FieldID,
	FieldDatasetVersionID,
	FieldCaseKey,
	FieldCapabilityDomain,
	FieldPriority,
	FieldWeight,
	FieldSampleCount,
	FieldPromptSpec,
	FieldExpectedSpec,
	FieldEncryptedSpec,
	FieldExecutionSpec,
	FieldQualityDimension,
	FieldQualityProbeSpec,
	FieldGraderID,
	FieldGraderVersion,
	FieldContentSha256,
	FieldConfidentiality,
	FieldEstimatedCost,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CaseKeyValidator is a validator for the "case_key" field. It is called by the builders before save.
	CaseKeyValidator func(string) error
	// CapabilityDomainValidator is a validator for the "capability_domain" field. It is called by the builders before save.
	CapabilityDomainValidator func(string) error
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(string) error
	// DefaultQualityProbeSpec holds the default value on creation for the "quality_probe_spec" field.
	DefaultQualityProbeSpec map[string]interface{}
	// GraderIDValidator is a validator for the "grader_id" field. It is called by the builders before save.
	GraderIDValidator func(string) error
	// GraderVersionValidator is a validator for the "grader_version" field. It is called by the builders before save.
	GraderVersionValidator func(string) error
	// ContentSha256Validator is a validator for the "content_sha256" field. It is called by the builders before save.
	ContentSha256Validator func(string) error
	// ConfidentialityValidator is a validator for the "confidentiality" field. It is called by the builders before save.
	ConfidentialityValidator func(string) error
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EvaluationCase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDatasetVersionID orders the results by the dataset_version_id field.
func ByDatasetVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatasetVersionID, opts...).ToFunc()
}

// ByCaseKey orders the results by the case_key field.
func ByCaseKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaseKey, opts...).ToFunc()
}

// ByCapabilityDomain orders the results by the capability_domain field.
func ByCapabilityDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityDomain, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// BySampleCount orders the results by the sample_count field.
func BySampleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleCount, opts...).ToFunc()
}

// ByEncryptedSpec orders the results by the encrypted_spec field.
func ByEncryptedSpec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedSpec, opts...).ToFunc()
}

// ByQualityDimension orders the results by the quality_dimension field.
func ByQualityDimension(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityDimension, opts...).ToFunc()
}

// ByGraderID orders the results by the grader_id field.
func ByGraderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGraderID, opts...).ToFunc()
}

// ByGraderVersion orders the results by the grader_version field.
func ByGraderVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGraderVersion, opts...).ToFunc()
}

// ByContentSha256 orders the results by the content_sha256 field.
func ByContentSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentSha256, opts...).ToFunc()
}

// ByConfidentiality orders the results by the confidentiality field.
func ByConfidentiality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidentiality, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDatasetVersionField orders the results by dataset_version field.
func ByDatasetVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatasetVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newDatasetVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatasetVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DatasetVersionTable, DatasetVersionColumn),
	)
}
