// Code generated by ent, DO NOT EDIT.

package evaluationcase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldID, id))
}

// DatasetVersionID applies equality check predicate on the "dataset_version_id" field. It's identical to DatasetVersionIDEQ.
func DatasetVersionID(v uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldDatasetVersionID, v))
}

// CaseKey applies equality check predicate on the "case_key" field. It's identical to CaseKeyEQ.
func CaseKey(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCaseKey, v))
}

// CapabilityDomain applies equality check predicate on the "capability_domain" field. It's identical to CapabilityDomainEQ.
func CapabilityDomain(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCapabilityDomain, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldWeight, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldSampleCount, v))
}

// EncryptedSpec applies equality check predicate on the "encrypted_spec" field. It's identical to EncryptedSpecEQ.
func EncryptedSpec(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldEncryptedSpec, v))
}

// QualityDimension applies equality check predicate on the "quality_dimension" field. It's identical to QualityDimensionEQ.
func QualityDimension(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldQualityDimension, v))
}

// GraderID applies equality check predicate on the "grader_id" field. It's identical to GraderIDEQ.
func GraderID(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldGraderID, v))
}

// GraderVersion applies equality check predicate on the "grader_version" field. It's identical to GraderVersionEQ.
func GraderVersion(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldGraderVersion, v))
}

// ContentSha256 applies equality check predicate on the "content_sha256" field. It's identical to ContentSha256EQ.
func ContentSha256(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldContentSha256, v))
}

// Confidentiality applies equality check predicate on the "confidentiality" field. It's identical to ConfidentialityEQ.
func Confidentiality(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldConfidentiality, v))
}

// EstimatedCost applies equality check predicate on the "estimated_cost" field. It's identical to EstimatedCostEQ.
func EstimatedCost(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldEstimatedCost, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCreatedAt, v))
}

// DatasetVersionIDEQ applies the EQ predicate on the "dataset_version_id" field.
func DatasetVersionIDEQ(v uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldDatasetVersionID, v))
}

// DatasetVersionIDNEQ applies the NEQ predicate on the "dataset_version_id" field.
func DatasetVersionIDNEQ(v uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldDatasetVersionID, v))
}

// DatasetVersionIDIn applies the In predicate on the "dataset_version_id" field.
func DatasetVersionIDIn(vs ...uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldDatasetVersionID, vs...))
}

// DatasetVersionIDNotIn applies the NotIn predicate on the "dataset_version_id" field.
func DatasetVersionIDNotIn(vs ...uuid.UUID) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldDatasetVersionID, vs...))
}

// CaseKeyEQ applies the EQ predicate on the "case_key" field.
func CaseKeyEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCaseKey, v))
}

// CaseKeyNEQ applies the NEQ predicate on the "case_key" field.
func CaseKeyNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldCaseKey, v))
}

// CaseKeyIn applies the In predicate on the "case_key" field.
func CaseKeyIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldCaseKey, vs...))
}

// CaseKeyNotIn applies the NotIn predicate on the "case_key" field.
func CaseKeyNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldCaseKey, vs...))
}

// CaseKeyGT applies the GT predicate on the "case_key" field.
func CaseKeyGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldCaseKey, v))
}

// CaseKeyGTE applies the GTE predicate on the "case_key" field.
func CaseKeyGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldCaseKey, v))
}

// CaseKeyLT applies the LT predicate on the "case_key" field.
func CaseKeyLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldCaseKey, v))
}

// CaseKeyLTE applies the LTE predicate on the "case_key" field.
func CaseKeyLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldCaseKey, v))
}

// CaseKeyContains applies the Contains predicate on the "case_key" field.
func CaseKeyContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldCaseKey, v))
}

// CaseKeyHasPrefix applies the HasPrefix predicate on the "case_key" field.
func CaseKeyHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldCaseKey, v))
}

// CaseKeyHasSuffix applies the HasSuffix predicate on the "case_key" field.
func CaseKeyHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldCaseKey, v))
}

// CaseKeyEqualFold applies the EqualFold predicate on the "case_key" field.
func CaseKeyEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldCaseKey, v))
}

// CaseKeyContainsFold applies the ContainsFold predicate on the "case_key" field.
func CaseKeyContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldCaseKey, v))
}

// CapabilityDomainEQ applies the EQ predicate on the "capability_domain" field.
func CapabilityDomainEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCapabilityDomain, v))
}

// CapabilityDomainNEQ applies the NEQ predicate on the "capability_domain" field.
func CapabilityDomainNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldCapabilityDomain, v))
}

// CapabilityDomainIn applies the In predicate on the "capability_domain" field.
func CapabilityDomainIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldCapabilityDomain, vs...))
}

// CapabilityDomainNotIn applies the NotIn predicate on the "capability_domain" field.
func CapabilityDomainNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldCapabilityDomain, vs...))
}

// CapabilityDomainGT applies the GT predicate on the "capability_domain" field.
func CapabilityDomainGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldCapabilityDomain, v))
}

// CapabilityDomainGTE applies the GTE predicate on the "capability_domain" field.
func CapabilityDomainGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldCapabilityDomain, v))
}

// CapabilityDomainLT applies the LT predicate on the "capability_domain" field.
func CapabilityDomainLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldCapabilityDomain, v))
}

// CapabilityDomainLTE applies the LTE predicate on the "capability_domain" field.
func CapabilityDomainLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldCapabilityDomain, v))
}

// CapabilityDomainContains applies the Contains predicate on the "capability_domain" field.
func CapabilityDomainContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldCapabilityDomain, v))
}

// CapabilityDomainHasPrefix applies the HasPrefix predicate on the "capability_domain" field.
func CapabilityDomainHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldCapabilityDomain, v))
}

// CapabilityDomainHasSuffix applies the HasSuffix predicate on the "capability_domain" field.
func CapabilityDomainHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldCapabilityDomain, v))
}

// CapabilityDomainEqualFold applies the EqualFold predicate on the "capability_domain" field.
func CapabilityDomainEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldCapabilityDomain, v))
}

// CapabilityDomainContainsFold applies the ContainsFold predicate on the "capability_domain" field.
func CapabilityDomainContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldCapabilityDomain, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldWeight, v))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldSampleCount, v))
}

// PromptSpecIsNil applies the IsNil predicate on the "prompt_spec" field.
func PromptSpecIsNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIsNull(FieldPromptSpec))
}

// PromptSpecNotNil applies the NotNil predicate on the "prompt_spec" field.
func PromptSpecNotNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotNull(FieldPromptSpec))
}

// ExpectedSpecIsNil applies the IsNil predicate on the "expected_spec" field.
func ExpectedSpecIsNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIsNull(FieldExpectedSpec))
}

// ExpectedSpecNotNil applies the NotNil predicate on the "expected_spec" field.
func ExpectedSpecNotNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotNull(FieldExpectedSpec))
}

// EncryptedSpecEQ applies the EQ predicate on the "encrypted_spec" field.
func EncryptedSpecEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldEncryptedSpec, v))
}

// EncryptedSpecNEQ applies the NEQ predicate on the "encrypted_spec" field.
func EncryptedSpecNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldEncryptedSpec, v))
}

// EncryptedSpecIn applies the In predicate on the "encrypted_spec" field.
func EncryptedSpecIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldEncryptedSpec, vs...))
}

// EncryptedSpecNotIn applies the NotIn predicate on the "encrypted_spec" field.
func EncryptedSpecNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldEncryptedSpec, vs...))
}

// EncryptedSpecGT applies the GT predicate on the "encrypted_spec" field.
func EncryptedSpecGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldEncryptedSpec, v))
}

// EncryptedSpecGTE applies the GTE predicate on the "encrypted_spec" field.
func EncryptedSpecGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldEncryptedSpec, v))
}

// EncryptedSpecLT applies the LT predicate on the "encrypted_spec" field.
func EncryptedSpecLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldEncryptedSpec, v))
}

// EncryptedSpecLTE applies the LTE predicate on the "encrypted_spec" field.
func EncryptedSpecLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldEncryptedSpec, v))
}

// EncryptedSpecContains applies the Contains predicate on the "encrypted_spec" field.
func EncryptedSpecContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldEncryptedSpec, v))
}

// EncryptedSpecHasPrefix applies the HasPrefix predicate on the "encrypted_spec" field.
func EncryptedSpecHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldEncryptedSpec, v))
}

// EncryptedSpecHasSuffix applies the HasSuffix predicate on the "encrypted_spec" field.
func EncryptedSpecHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldEncryptedSpec, v))
}

// EncryptedSpecIsNil applies the IsNil predicate on the "encrypted_spec" field.
func EncryptedSpecIsNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIsNull(FieldEncryptedSpec))
}

// EncryptedSpecNotNil applies the NotNil predicate on the "encrypted_spec" field.
func EncryptedSpecNotNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotNull(FieldEncryptedSpec))
}

// EncryptedSpecEqualFold applies the EqualFold predicate on the "encrypted_spec" field.
func EncryptedSpecEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldEncryptedSpec, v))
}

// EncryptedSpecContainsFold applies the ContainsFold predicate on the "encrypted_spec" field.
func EncryptedSpecContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldEncryptedSpec, v))
}

// QualityDimensionEQ applies the EQ predicate on the "quality_dimension" field.
func QualityDimensionEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldQualityDimension, v))
}

// QualityDimensionNEQ applies the NEQ predicate on the "quality_dimension" field.
func QualityDimensionNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldQualityDimension, v))
}

// QualityDimensionIn applies the In predicate on the "quality_dimension" field.
func QualityDimensionIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldQualityDimension, vs...))
}

// QualityDimensionNotIn applies the NotIn predicate on the "quality_dimension" field.
func QualityDimensionNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldQualityDimension, vs...))
}

// QualityDimensionGT applies the GT predicate on the "quality_dimension" field.
func QualityDimensionGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldQualityDimension, v))
}

// QualityDimensionGTE applies the GTE predicate on the "quality_dimension" field.
func QualityDimensionGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldQualityDimension, v))
}

// QualityDimensionLT applies the LT predicate on the "quality_dimension" field.
func QualityDimensionLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldQualityDimension, v))
}

// QualityDimensionLTE applies the LTE predicate on the "quality_dimension" field.
func QualityDimensionLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldQualityDimension, v))
}

// QualityDimensionContains applies the Contains predicate on the "quality_dimension" field.
func QualityDimensionContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldQualityDimension, v))
}

// QualityDimensionHasPrefix applies the HasPrefix predicate on the "quality_dimension" field.
func QualityDimensionHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldQualityDimension, v))
}

// QualityDimensionHasSuffix applies the HasSuffix predicate on the "quality_dimension" field.
func QualityDimensionHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldQualityDimension, v))
}

// QualityDimensionIsNil applies the IsNil predicate on the "quality_dimension" field.
func QualityDimensionIsNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIsNull(FieldQualityDimension))
}

// QualityDimensionNotNil applies the NotNil predicate on the "quality_dimension" field.
func QualityDimensionNotNil() predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotNull(FieldQualityDimension))
}

// QualityDimensionEqualFold applies the EqualFold predicate on the "quality_dimension" field.
func QualityDimensionEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldQualityDimension, v))
}

// QualityDimensionContainsFold applies the ContainsFold predicate on the "quality_dimension" field.
func QualityDimensionContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldQualityDimension, v))
}

// GraderIDEQ applies the EQ predicate on the "grader_id" field.
func GraderIDEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldGraderID, v))
}

// GraderIDNEQ applies the NEQ predicate on the "grader_id" field.
func GraderIDNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldGraderID, v))
}

// GraderIDIn applies the In predicate on the "grader_id" field.
func GraderIDIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldGraderID, vs...))
}

// GraderIDNotIn applies the NotIn predicate on the "grader_id" field.
func GraderIDNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldGraderID, vs...))
}

// GraderIDGT applies the GT predicate on the "grader_id" field.
func GraderIDGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldGraderID, v))
}

// GraderIDGTE applies the GTE predicate on the "grader_id" field.
func GraderIDGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldGraderID, v))
}

// GraderIDLT applies the LT predicate on the "grader_id" field.
func GraderIDLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldGraderID, v))
}

// GraderIDLTE applies the LTE predicate on the "grader_id" field.
func GraderIDLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldGraderID, v))
}

// GraderIDContains applies the Contains predicate on the "grader_id" field.
func GraderIDContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldGraderID, v))
}

// GraderIDHasPrefix applies the HasPrefix predicate on the "grader_id" field.
func GraderIDHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldGraderID, v))
}

// GraderIDHasSuffix applies the HasSuffix predicate on the "grader_id" field.
func GraderIDHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldGraderID, v))
}

// GraderIDEqualFold applies the EqualFold predicate on the "grader_id" field.
func GraderIDEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldGraderID, v))
}

// GraderIDContainsFold applies the ContainsFold predicate on the "grader_id" field.
func GraderIDContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldGraderID, v))
}

// GraderVersionEQ applies the EQ predicate on the "grader_version" field.
func GraderVersionEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldGraderVersion, v))
}

// GraderVersionNEQ applies the NEQ predicate on the "grader_version" field.
func GraderVersionNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldGraderVersion, v))
}

// GraderVersionIn applies the In predicate on the "grader_version" field.
func GraderVersionIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldGraderVersion, vs...))
}

// GraderVersionNotIn applies the NotIn predicate on the "grader_version" field.
func GraderVersionNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldGraderVersion, vs...))
}

// GraderVersionGT applies the GT predicate on the "grader_version" field.
func GraderVersionGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldGraderVersion, v))
}

// GraderVersionGTE applies the GTE predicate on the "grader_version" field.
func GraderVersionGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldGraderVersion, v))
}

// GraderVersionLT applies the LT predicate on the "grader_version" field.
func GraderVersionLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldGraderVersion, v))
}

// GraderVersionLTE applies the LTE predicate on the "grader_version" field.
func GraderVersionLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldGraderVersion, v))
}

// GraderVersionContains applies the Contains predicate on the "grader_version" field.
func GraderVersionContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldGraderVersion, v))
}

// GraderVersionHasPrefix applies the HasPrefix predicate on the "grader_version" field.
func GraderVersionHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldGraderVersion, v))
}

// GraderVersionHasSuffix applies the HasSuffix predicate on the "grader_version" field.
func GraderVersionHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldGraderVersion, v))
}

// GraderVersionEqualFold applies the EqualFold predicate on the "grader_version" field.
func GraderVersionEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldGraderVersion, v))
}

// GraderVersionContainsFold applies the ContainsFold predicate on the "grader_version" field.
func GraderVersionContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldGraderVersion, v))
}

// ContentSha256EQ applies the EQ predicate on the "content_sha256" field.
func ContentSha256EQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldContentSha256, v))
}

// ContentSha256NEQ applies the NEQ predicate on the "content_sha256" field.
func ContentSha256NEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldContentSha256, v))
}

// ContentSha256In applies the In predicate on the "content_sha256" field.
func ContentSha256In(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldContentSha256, vs...))
}

// ContentSha256NotIn applies the NotIn predicate on the "content_sha256" field.
func ContentSha256NotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldContentSha256, vs...))
}

// ContentSha256GT applies the GT predicate on the "content_sha256" field.
func ContentSha256GT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldContentSha256, v))
}

// ContentSha256GTE applies the GTE predicate on the "content_sha256" field.
func ContentSha256GTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldContentSha256, v))
}

// ContentSha256LT applies the LT predicate on the "content_sha256" field.
func ContentSha256LT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldContentSha256, v))
}

// ContentSha256LTE applies the LTE predicate on the "content_sha256" field.
func ContentSha256LTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldContentSha256, v))
}

// ContentSha256Contains applies the Contains predicate on the "content_sha256" field.
func ContentSha256Contains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldContentSha256, v))
}

// ContentSha256HasPrefix applies the HasPrefix predicate on the "content_sha256" field.
func ContentSha256HasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldContentSha256, v))
}

// ContentSha256HasSuffix applies the HasSuffix predicate on the "content_sha256" field.
func ContentSha256HasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldContentSha256, v))
}

// ContentSha256EqualFold applies the EqualFold predicate on the "content_sha256" field.
func ContentSha256EqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldContentSha256, v))
}

// ContentSha256ContainsFold applies the ContainsFold predicate on the "content_sha256" field.
func ContentSha256ContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldContentSha256, v))
}

// ConfidentialityEQ applies the EQ predicate on the "confidentiality" field.
func ConfidentialityEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldConfidentiality, v))
}

// ConfidentialityNEQ applies the NEQ predicate on the "confidentiality" field.
func ConfidentialityNEQ(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldConfidentiality, v))
}

// ConfidentialityIn applies the In predicate on the "confidentiality" field.
func ConfidentialityIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldConfidentiality, vs...))
}

// ConfidentialityNotIn applies the NotIn predicate on the "confidentiality" field.
func ConfidentialityNotIn(vs ...string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldConfidentiality, vs...))
}

// ConfidentialityGT applies the GT predicate on the "confidentiality" field.
func ConfidentialityGT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldConfidentiality, v))
}

// ConfidentialityGTE applies the GTE predicate on the "confidentiality" field.
func ConfidentialityGTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldConfidentiality, v))
}

// ConfidentialityLT applies the LT predicate on the "confidentiality" field.
func ConfidentialityLT(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldConfidentiality, v))
}

// ConfidentialityLTE applies the LTE predicate on the "confidentiality" field.
func ConfidentialityLTE(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldConfidentiality, v))
}

// ConfidentialityContains applies the Contains predicate on the "confidentiality" field.
func ConfidentialityContains(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContains(FieldConfidentiality, v))
}

// ConfidentialityHasPrefix applies the HasPrefix predicate on the "confidentiality" field.
func ConfidentialityHasPrefix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasPrefix(FieldConfidentiality, v))
}

// ConfidentialityHasSuffix applies the HasSuffix predicate on the "confidentiality" field.
func ConfidentialityHasSuffix(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldHasSuffix(FieldConfidentiality, v))
}

// ConfidentialityEqualFold applies the EqualFold predicate on the "confidentiality" field.
func ConfidentialityEqualFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEqualFold(FieldConfidentiality, v))
}

// ConfidentialityContainsFold applies the ContainsFold predicate on the "confidentiality" field.
func ConfidentialityContainsFold(v string) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldContainsFold(FieldConfidentiality, v))
}

// EstimatedCostEQ applies the EQ predicate on the "estimated_cost" field.
func EstimatedCostEQ(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldEstimatedCost, v))
}

// EstimatedCostNEQ applies the NEQ predicate on the "estimated_cost" field.
func EstimatedCostNEQ(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldEstimatedCost, v))
}

// EstimatedCostIn applies the In predicate on the "estimated_cost" field.
func EstimatedCostIn(vs ...float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldEstimatedCost, vs...))
}

// EstimatedCostNotIn applies the NotIn predicate on the "estimated_cost" field.
func EstimatedCostNotIn(vs ...float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldEstimatedCost, vs...))
}

// EstimatedCostGT applies the GT predicate on the "estimated_cost" field.
func EstimatedCostGT(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldEstimatedCost, v))
}

// EstimatedCostGTE applies the GTE predicate on the "estimated_cost" field.
func EstimatedCostGTE(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldEstimatedCost, v))
}

// EstimatedCostLT applies the LT predicate on the "estimated_cost" field.
func EstimatedCostLT(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldEstimatedCost, v))
}

// EstimatedCostLTE applies the LTE predicate on the "estimated_cost" field.
func EstimatedCostLTE(v float64) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldEstimatedCost, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDatasetVersion applies the HasEdge predicate on the "dataset_version" edge.
func HasDatasetVersion() predicate.EvaluationCase {
	return predicate.EvaluationCase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DatasetVersionTable, DatasetVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDatasetVersionWith applies the HasEdge predicate on the "dataset_version" edge with a given conditions (other predicates).
func HasDatasetVersionWith(preds ...predicate.EvaluationDatasetVersion) predicate.EvaluationCase {
	return predicate.EvaluationCase(func(s *sql.Selector) {
		step := newDatasetVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EvaluationCase) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EvaluationCase) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EvaluationCase) predicate.EvaluationCase {
	return predicate.EvaluationCase(sql.NotPredicates(p))
}
