// Code generated by ent, DO NOT EDIT.

package evaluationplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the evaluationplan type in the database.
	Label = "evaluation_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDatasetVersionID holds the string denoting the dataset_version_id field in the database.
	FieldDatasetVersionID = "dataset_version_id"
	// FieldGatewayAPIKeyID holds the string denoting the gateway_api_key_id field in the database.
	FieldGatewayAPIKeyID = "gateway_api_key_id"
	// FieldTriggerType holds the string denoting the trigger_type field in the database.
	FieldTriggerType = "trigger_type"
	// FieldCronExpression holds the string denoting the cron_expression field in the database.
	FieldCronExpression = "cron_expression"
	// FieldModelMatrix holds the string denoting the model_matrix field in the database.
	FieldModelMatrix = "model_matrix"
	// FieldMaxRunCost holds the string denoting the max_run_cost field in the database.
	FieldMaxRunCost = "max_run_cost"
	// FieldDailyCostLimit holds the string denoting the daily_cost_limit field in the database.
	FieldDailyCostLimit = "daily_cost_limit"
	// FieldMaxConcurrency holds the string denoting the max_concurrency field in the database.
	FieldMaxConcurrency = "max_concurrency"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDatasetVersion holds the string denoting the dataset_version edge name in mutations.
	EdgeDatasetVersion = "dataset_version"
	// EdgeGatewayAPIKey holds the string denoting the gateway_api_key edge name in mutations.
	EdgeGatewayAPIKey = "gateway_api_key"
	// EdgeRuns holds the string denoting the runs edge name in mutations.
	EdgeRuns = "runs"
	// Table holds the table name of the evaluationplan in the database.
	Table = "evaluation_plans"
	// DatasetVersionTable is the table that holds the dataset_version relation/edge.
	DatasetVersionTable = "evaluation_plans"
	// DatasetVersionInverseTable is the table name for the EvaluationDatasetVersion entity.
	// It exists in this package in order to avoid circular dependency with the "evaluationdatasetversion" package.
	DatasetVersionInverseTable = "evaluation_dataset_versions"
	// DatasetVersionColumn is the table column denoting the dataset_version relation/edge.
	DatasetVersionColumn = "dataset_version_id"
	// GatewayAPIKeyTable is the table that holds the gateway_api_key relation/edge.
	GatewayAPIKeyTable = "evaluation_plans"
	// GatewayAPIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	GatewayAPIKeyInverseTable = "api_keys"
	// GatewayAPIKeyColumn is the table column denoting the gateway_api_key relation/edge.
	GatewayAPIKeyColumn = "gateway_api_key_id"
	// RunsTable is the table that holds the runs relation/edge.
	RunsTable = "evaluation_runs"
	// RunsInverseTable is the table name for the EvaluationRun entity.
	// It exists in this package in order to avoid circular dependency with the "evaluationrun" package.
	RunsInverseTable = "evaluation_runs"
	// RunsColumn is the table column denoting the runs relation/edge.
	RunsColumn = "plan_id"
)

// Columns holds all SQL columns for evaluationplan fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDatasetVersionID,
	FieldGatewayAPIKeyID,
	FieldTriggerType,
	FieldCronExpression,
	FieldModelMatrix,
	FieldMaxRunCost,
	FieldDailyCostLimit,
	FieldMaxConcurrency,
	FieldEnabled,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TriggerTypeValidator is a validator for the "trigger_type" field. It is called by the builders before save.
	TriggerTypeValidator func(string) error
	// CronExpressionValidator is a validator for the "cron_expression" field. It is called by the builders before save.
	CronExpressionValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EvaluationPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDatasetVersionID orders the results by the dataset_version_id field.
func ByDatasetVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatasetVersionID, opts...).ToFunc()
}

// ByGatewayAPIKeyID orders the results by the gateway_api_key_id field.
func ByGatewayAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayAPIKeyID, opts...).ToFunc()
}

// ByTriggerType orders the results by the trigger_type field.
func ByTriggerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerType, opts...).ToFunc()
}

// ByCronExpression orders the results by the cron_expression field.
func ByCronExpression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCronExpression, opts...).ToFunc()
}

// ByMaxRunCost orders the results by the max_run_cost field.
func ByMaxRunCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRunCost, opts...).ToFunc()
}

// ByDailyCostLimit orders the results by the daily_cost_limit field.
func ByDailyCostLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyCostLimit, opts...).ToFunc()
}

// ByMaxConcurrency orders the results by the max_concurrency field.
func ByMaxConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxConcurrency, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDatasetVersionField orders the results by dataset_version field.
func ByDatasetVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatasetVersionStep(), sql.OrderByField(field, opts...))
	}
}

// ByGatewayAPIKeyField orders the results by gateway_api_key field.
func ByGatewayAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGatewayAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunsCount orders the results by runs count.
func ByRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRunsStep(), opts...)
	}
}

// ByRuns orders the results by runs terms.
func ByRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDatasetVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatasetVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DatasetVersionTable, DatasetVersionColumn),
	)
}
func newGatewayAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GatewayAPIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GatewayAPIKeyTable, GatewayAPIKeyColumn),
	)
}
func newRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RunsTable, RunsColumn),
	)
}
