// Code generated by ent, DO NOT EDIT.

package evaluationrouteevidence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the evaluationrouteevidence type in the database.
	Label = "evaluation_route_evidence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "route_trace_id"
	// FieldEvaluationRunID holds the string denoting the evaluation_run_id field in the database.
	FieldEvaluationRunID = "evaluation_run_id"
	// FieldSampleID holds the string denoting the sample_id field in the database.
	FieldSampleID = "sample_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldResolvedModel holds the string denoting the resolved_model field in the database.
	FieldResolvedModel = "resolved_model"
	// FieldRouteProfileVersion holds the string denoting the route_profile_version field in the database.
	FieldRouteProfileVersion = "route_profile_version"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldChannelRef holds the string denoting the channel_ref field in the database.
	FieldChannelRef = "channel_ref"
	// FieldAccountPoolRef holds the string denoting the account_pool_ref field in the database.
	FieldAccountPoolRef = "account_pool_ref"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldFallbackChain holds the string denoting the fallback_chain field in the database.
	FieldFallbackChain = "fallback_chain"
	// FieldFinishReason holds the string denoting the finish_reason field in the database.
	FieldFinishReason = "finish_reason"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTtftMs holds the string denoting the ttft_ms field in the database.
	FieldTtftMs = "ttft_ms"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldBilledAmount holds the string denoting the billed_amount field in the database.
	FieldBilledAmount = "billed_amount"
	// FieldTransportStatus holds the string denoting the transport_status field in the database.
	FieldTransportStatus = "transport_status"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// APIKeyFieldID holds the string denoting the ID field of the APIKey.
	APIKeyFieldID = "id"
	// Table holds the table name of the evaluationrouteevidence in the database.
	Table = "evaluation_route_evidence"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "evaluation_route_evidence"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
)

// Columns holds all SQL columns for evaluationrouteevidence fields.
var Columns = []string{
	FieldID,
	FieldEvaluationRunID,
	FieldSampleID,
	FieldAPIKeyID,
	FieldRequestID,
	FieldRequestedModel,
	FieldResolvedModel,
	FieldRouteProfileVersion,
	FieldProvider,
	FieldChannelRef,
	FieldAccountPoolRef,
	FieldRegion,
	FieldAttempts,
	FieldFallbackChain,
	FieldFinishReason,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTtftMs,
	FieldLatencyMs,
	FieldBilledAmount,
	FieldTransportStatus,
	FieldErrorCode,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// ResolvedModelValidator is a validator for the "resolved_model" field. It is called by the builders before save.
	ResolvedModelValidator func(string) error
	// RouteProfileVersionValidator is a validator for the "route_profile_version" field. It is called by the builders before save.
	RouteProfileVersionValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ChannelRefValidator is a validator for the "channel_ref" field. It is called by the builders before save.
	ChannelRefValidator func(string) error
	// AccountPoolRefValidator is a validator for the "account_pool_ref" field. It is called by the builders before save.
	AccountPoolRefValidator func(string) error
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// AttemptsValidator is a validator for the "attempts" field. It is called by the builders before save.
	AttemptsValidator func(int) error
	// FinishReasonValidator is a validator for the "finish_reason" field. It is called by the builders before save.
	FinishReasonValidator func(string) error
	// InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	InputTokensValidator func(int) error
	// OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	OutputTokensValidator func(int) error
	// TtftMsValidator is a validator for the "ttft_ms" field. It is called by the builders before save.
	TtftMsValidator func(int) error
	// LatencyMsValidator is a validator for the "latency_ms" field. It is called by the builders before save.
	LatencyMsValidator func(int) error
	// DefaultTransportStatus holds the default value on creation for the "transport_status" field.
	DefaultTransportStatus string
	// TransportStatusValidator is a validator for the "transport_status" field. It is called by the builders before save.
	TransportStatusValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the EvaluationRouteEvidence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEvaluationRunID orders the results by the evaluation_run_id field.
func ByEvaluationRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvaluationRunID, opts...).ToFunc()
}

// BySampleID orders the results by the sample_id field.
func BySampleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByResolvedModel orders the results by the resolved_model field.
func ByResolvedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedModel, opts...).ToFunc()
}

// ByRouteProfileVersion orders the results by the route_profile_version field.
func ByRouteProfileVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteProfileVersion, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByChannelRef orders the results by the channel_ref field.
func ByChannelRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelRef, opts...).ToFunc()
}

// ByAccountPoolRef orders the results by the account_pool_ref field.
func ByAccountPoolRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountPoolRef, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByFinishReason orders the results by the finish_reason field.
func ByFinishReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishReason, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTtftMs orders the results by the ttft_ms field.
func ByTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftMs, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByBilledAmount orders the results by the billed_amount field.
func ByBilledAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBilledAmount, opts...).ToFunc()
}

// ByTransportStatus orders the results by the transport_status field.
func ByTransportStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransportStatus, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, APIKeyFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
