// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/evaluationplan"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrun"
	"github.com/google/uuid"
)

// EvaluationRun is the model entity for the EvaluationRun schema.
type EvaluationRun struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID uuid.UUID `json:"plan_id,omitempty"`
	// TriggerSource holds the value of the "trigger_source" field.
	TriggerSource string `json:"trigger_source,omitempty"`
	// BaselineRef holds the value of the "baseline_ref" field.
	BaselineRef map[string]interface{} `json:"baseline_ref,omitempty"`
	// CandidateRef holds the value of the "candidate_ref" field.
	CandidateRef map[string]interface{} `json:"candidate_ref,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// BudgetLimit holds the value of the "budget_limit" field.
	BudgetLimit float64 `json:"budget_limit,omitempty"`
	// ReservedCost holds the value of the "reserved_cost" field.
	ReservedCost float64 `json:"reserved_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// CalibrationMode holds the value of the "calibration_mode" field.
	CalibrationMode bool `json:"calibration_mode,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EvaluationRunQuery when eager-loading is set.
	Edges        EvaluationRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EvaluationRunEdges holds the relations/edges for other nodes in the graph.
type EvaluationRunEdges struct {
	// Plan holds the value of the plan edge.
	Plan *EvaluationPlan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EvaluationRunEdges) PlanOrErr() (*EvaluationPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: evaluationplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EvaluationRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case evaluationrun.FieldBaselineRef, evaluationrun.FieldCandidateRef:
			values[i] = new([]byte)
		case evaluationrun.FieldCalibrationMode:
			values[i] = new(sql.NullBool)
		case evaluationrun.FieldBudgetLimit, evaluationrun.FieldReservedCost, evaluationrun.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case evaluationrun.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case evaluationrun.FieldTriggerSource, evaluationrun.FieldStatus:
			values[i] = new(sql.NullString)
		case evaluationrun.FieldStartedAt, evaluationrun.FieldFinishedAt, evaluationrun.FieldCreatedAt, evaluationrun.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case evaluationrun.FieldID, evaluationrun.FieldPlanID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EvaluationRun fields.
func (_m *EvaluationRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case evaluationrun.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case evaluationrun.FieldPlanID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value != nil {
				_m.PlanID = *value
			}
		case evaluationrun.FieldTriggerSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_source", values[i])
			} else if value.Valid {
				_m.TriggerSource = value.String
			}
		case evaluationrun.FieldBaselineRef:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field baseline_ref", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BaselineRef); err != nil {
					return fmt.Errorf("unmarshal field baseline_ref: %w", err)
				}
			}
		case evaluationrun.FieldCandidateRef:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_ref", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CandidateRef); err != nil {
					return fmt.Errorf("unmarshal field candidate_ref: %w", err)
				}
			}
		case evaluationrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case evaluationrun.FieldBudgetLimit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field budget_limit", values[i])
			} else if value.Valid {
				_m.BudgetLimit = value.Float64
			}
		case evaluationrun.FieldReservedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_cost", values[i])
			} else if value.Valid {
				_m.ReservedCost = value.Float64
			}
		case evaluationrun.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case evaluationrun.FieldCalibrationMode:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field calibration_mode", values[i])
			} else if value.Valid {
				_m.CalibrationMode = value.Bool
			}
		case evaluationrun.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case evaluationrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case evaluationrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case evaluationrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case evaluationrun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EvaluationRun.
// This includes values selected through modifiers, order, etc.
func (_m *EvaluationRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the EvaluationRun entity.
func (_m *EvaluationRun) QueryPlan() *EvaluationPlanQuery {
	return NewEvaluationRunClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this EvaluationRun.
// Note that you need to call EvaluationRun.Unwrap() before calling this method if this EvaluationRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EvaluationRun) Update() *EvaluationRunUpdateOne {
	return NewEvaluationRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EvaluationRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EvaluationRun) Unwrap() *EvaluationRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EvaluationRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EvaluationRun) String() string {
	var builder strings.Builder
	builder.WriteString("EvaluationRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("trigger_source=")
	builder.WriteString(_m.TriggerSource)
	builder.WriteString(", ")
	builder.WriteString("baseline_ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaselineRef))
	builder.WriteString(", ")
	builder.WriteString("candidate_ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateRef))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("budget_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.BudgetLimit))
	builder.WriteString(", ")
	builder.WriteString("reserved_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("calibration_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.CalibrationMode))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EvaluationRuns is a parsable slice of EvaluationRun.
type EvaluationRuns []*EvaluationRun
