// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/evaluationdatasetversion"
	"github.com/Wei-Shaw/sub2api/ent/evaluationplan"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// EvaluationPlanQuery is the builder for querying EvaluationPlan entities.
type EvaluationPlanQuery struct {
	config
	ctx                *QueryContext
	order              []evaluationplan.OrderOption
	inters             []Interceptor
	predicates         []predicate.EvaluationPlan
	withDatasetVersion *EvaluationDatasetVersionQuery
	withGatewayAPIKey  *APIKeyQuery
	withRuns           *EvaluationRunQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EvaluationPlanQuery builder.
func (_q *EvaluationPlanQuery) Where(ps ...predicate.EvaluationPlan) *EvaluationPlanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EvaluationPlanQuery) Limit(limit int) *EvaluationPlanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EvaluationPlanQuery) Offset(offset int) *EvaluationPlanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EvaluationPlanQuery) Unique(unique bool) *EvaluationPlanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EvaluationPlanQuery) Order(o ...evaluationplan.OrderOption) *EvaluationPlanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDatasetVersion chains the current query on the "dataset_version" edge.
func (_q *EvaluationPlanQuery) QueryDatasetVersion() *EvaluationDatasetVersionQuery {
	query := (&EvaluationDatasetVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationplan.Table, evaluationplan.FieldID, selector),
			sqlgraph.To(evaluationdatasetversion.Table, evaluationdatasetversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, evaluationplan.DatasetVersionTable, evaluationplan.DatasetVersionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGatewayAPIKey chains the current query on the "gateway_api_key" edge.
func (_q *EvaluationPlanQuery) QueryGatewayAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationplan.Table, evaluationplan.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, evaluationplan.GatewayAPIKeyTable, evaluationplan.GatewayAPIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRuns chains the current query on the "runs" edge.
func (_q *EvaluationPlanQuery) QueryRuns() *EvaluationRunQuery {
	query := (&EvaluationRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationplan.Table, evaluationplan.FieldID, selector),
			sqlgraph.To(evaluationrun.Table, evaluationrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evaluationplan.RunsTable, evaluationplan.RunsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EvaluationPlan entity from the query.
// Returns a *NotFoundError when no EvaluationPlan was found.
func (_q *EvaluationPlanQuery) First(ctx context.Context) (*EvaluationPlan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{evaluationplan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EvaluationPlanQuery) FirstX(ctx context.Context) *EvaluationPlan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EvaluationPlan ID from the query.
// Returns a *NotFoundError when no EvaluationPlan ID was found.
func (_q *EvaluationPlanQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{evaluationplan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EvaluationPlanQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EvaluationPlan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EvaluationPlan entity is found.
// Returns a *NotFoundError when no EvaluationPlan entities are found.
func (_q *EvaluationPlanQuery) Only(ctx context.Context) (*EvaluationPlan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{evaluationplan.Label}
	default:
		return nil, &NotSingularError{evaluationplan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EvaluationPlanQuery) OnlyX(ctx context.Context) *EvaluationPlan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EvaluationPlan ID in the query.
// Returns a *NotSingularError when more than one EvaluationPlan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EvaluationPlanQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{evaluationplan.Label}
	default:
		err = &NotSingularError{evaluationplan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EvaluationPlanQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EvaluationPlans.
func (_q *EvaluationPlanQuery) All(ctx context.Context) ([]*EvaluationPlan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EvaluationPlan, *EvaluationPlanQuery]()
	return withInterceptors[[]*EvaluationPlan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EvaluationPlanQuery) AllX(ctx context.Context) []*EvaluationPlan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EvaluationPlan IDs.
func (_q *EvaluationPlanQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(evaluationplan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EvaluationPlanQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EvaluationPlanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EvaluationPlanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EvaluationPlanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EvaluationPlanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EvaluationPlanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EvaluationPlanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EvaluationPlanQuery) Clone() *EvaluationPlanQuery {
	if _q == nil {
		return nil
	}
	return &EvaluationPlanQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]evaluationplan.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.EvaluationPlan{}, _q.predicates...),
		withDatasetVersion: _q.withDatasetVersion.Clone(),
		withGatewayAPIKey:  _q.withGatewayAPIKey.Clone(),
		withRuns:           _q.withRuns.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDatasetVersion tells the query-builder to eager-load the nodes that are connected to
// the "dataset_version" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationPlanQuery) WithDatasetVersion(opts ...func(*EvaluationDatasetVersionQuery)) *EvaluationPlanQuery {
	query := (&EvaluationDatasetVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDatasetVersion = query
	return _q
}

// WithGatewayAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "gateway_api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationPlanQuery) WithGatewayAPIKey(opts ...func(*APIKeyQuery)) *EvaluationPlanQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGatewayAPIKey = query
	return _q
}

// WithRuns tells the query-builder to eager-load the nodes that are connected to
// the "runs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationPlanQuery) WithRuns(opts ...func(*EvaluationRunQuery)) *EvaluationPlanQuery {
	query := (&EvaluationRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRuns = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EvaluationPlan.Query().
//		GroupBy(evaluationplan.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EvaluationPlanQuery) GroupBy(field string, fields ...string) *EvaluationPlanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EvaluationPlanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = evaluationplan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.EvaluationPlan.Query().
//		Select(evaluationplan.FieldName).
//		Scan(ctx, &v)
func (_q *EvaluationPlanQuery) Select(fields ...string) *EvaluationPlanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EvaluationPlanSelect{EvaluationPlanQuery: _q}
	sbuild.label = evaluationplan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EvaluationPlanSelect configured with the given aggregations.
func (_q *EvaluationPlanQuery) Aggregate(fns ...AggregateFunc) *EvaluationPlanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EvaluationPlanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !evaluationplan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EvaluationPlanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EvaluationPlan, error) {
	var (
		nodes       = []*EvaluationPlan{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withDatasetVersion != nil,
			_q.withGatewayAPIKey != nil,
			_q.withRuns != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EvaluationPlan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EvaluationPlan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDatasetVersion; query != nil {
		if err := _q.loadDatasetVersion(ctx, query, nodes, nil,
			func(n *EvaluationPlan, e *EvaluationDatasetVersion) { n.Edges.DatasetVersion = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGatewayAPIKey; query != nil {
		if err := _q.loadGatewayAPIKey(ctx, query, nodes, nil,
			func(n *EvaluationPlan, e *APIKey) { n.Edges.GatewayAPIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRuns; query != nil {
		if err := _q.loadRuns(ctx, query, nodes,
			func(n *EvaluationPlan) { n.Edges.Runs = []*EvaluationRun{} },
			func(n *EvaluationPlan, e *EvaluationRun) { n.Edges.Runs = append(n.Edges.Runs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EvaluationPlanQuery) loadDatasetVersion(ctx context.Context, query *EvaluationDatasetVersionQuery, nodes []*EvaluationPlan, init func(*EvaluationPlan), assign func(*EvaluationPlan, *EvaluationDatasetVersion)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EvaluationPlan)
	for i := range nodes {
		fk := nodes[i].DatasetVersionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(evaluationdatasetversion.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "dataset_version_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EvaluationPlanQuery) loadGatewayAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*EvaluationPlan, init func(*EvaluationPlan), assign func(*EvaluationPlan, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*EvaluationPlan)
	for i := range nodes {
		if nodes[i].GatewayAPIKeyID == nil {
			continue
		}
		fk := *nodes[i].GatewayAPIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "gateway_api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EvaluationPlanQuery) loadRuns(ctx context.Context, query *EvaluationRunQuery, nodes []*EvaluationPlan, init func(*EvaluationPlan), assign func(*EvaluationPlan, *EvaluationRun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*EvaluationPlan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(evaluationrun.FieldPlanID)
	}
	query.Where(predicate.EvaluationRun(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evaluationplan.RunsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PlanID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EvaluationPlanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EvaluationPlanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(evaluationplan.Table, evaluationplan.Columns, sqlgraph.NewFieldSpec(evaluationplan.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationplan.FieldID)
		for i := range fields {
			if fields[i] != evaluationplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDatasetVersion != nil {
			_spec.Node.AddColumnOnce(evaluationplan.FieldDatasetVersionID)
		}
		if _q.withGatewayAPIKey != nil {
			_spec.Node.AddColumnOnce(evaluationplan.FieldGatewayAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EvaluationPlanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(evaluationplan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = evaluationplan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *EvaluationPlanQuery) ForUpdate(opts ...sql.LockOption) *EvaluationPlanQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *EvaluationPlanQuery) ForShare(opts ...sql.LockOption) *EvaluationPlanQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// EvaluationPlanGroupBy is the group-by builder for EvaluationPlan entities.
type EvaluationPlanGroupBy struct {
	selector
	build *EvaluationPlanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EvaluationPlanGroupBy) Aggregate(fns ...AggregateFunc) *EvaluationPlanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EvaluationPlanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationPlanQuery, *EvaluationPlanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EvaluationPlanGroupBy) sqlScan(ctx context.Context, root *EvaluationPlanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EvaluationPlanSelect is the builder for selecting fields of EvaluationPlan entities.
type EvaluationPlanSelect struct {
	*EvaluationPlanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EvaluationPlanSelect) Aggregate(fns ...AggregateFunc) *EvaluationPlanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EvaluationPlanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationPlanQuery, *EvaluationPlanSelect](ctx, _s.EvaluationPlanQuery, _s, _s.inters, v)
}

func (_s *EvaluationPlanSelect) sqlScan(ctx context.Context, root *EvaluationPlanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
