// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrouteevidence"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EvaluationRouteEvidenceUpdate is the builder for updating EvaluationRouteEvidence entities.
type EvaluationRouteEvidenceUpdate struct {
	config
	hooks    []Hook
	mutation *EvaluationRouteEvidenceMutation
}

// Where appends a list predicates to the EvaluationRouteEvidenceUpdate builder.
func (_u *EvaluationRouteEvidenceUpdate) Where(ps ...predicate.EvaluationRouteEvidence) *EvaluationRouteEvidenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *EvaluationRouteEvidenceUpdate) SetRequestID(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableRequestID(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearRequestID() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetResolvedModel sets the "resolved_model" field.
func (_u *EvaluationRouteEvidenceUpdate) SetResolvedModel(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetResolvedModel(v)
	return _u
}

// SetNillableResolvedModel sets the "resolved_model" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableResolvedModel(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetResolvedModel(*v)
	}
	return _u
}

// ClearResolvedModel clears the value of the "resolved_model" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearResolvedModel() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearResolvedModel()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *EvaluationRouteEvidenceUpdate) SetProvider(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableProvider(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearProvider() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetChannelRef sets the "channel_ref" field.
func (_u *EvaluationRouteEvidenceUpdate) SetChannelRef(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetChannelRef(v)
	return _u
}

// SetNillableChannelRef sets the "channel_ref" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableChannelRef(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetChannelRef(*v)
	}
	return _u
}

// ClearChannelRef clears the value of the "channel_ref" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearChannelRef() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearChannelRef()
	return _u
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (_u *EvaluationRouteEvidenceUpdate) SetAccountPoolRef(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetAccountPoolRef(v)
	return _u
}

// SetNillableAccountPoolRef sets the "account_pool_ref" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableAccountPoolRef(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetAccountPoolRef(*v)
	}
	return _u
}

// ClearAccountPoolRef clears the value of the "account_pool_ref" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearAccountPoolRef() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearAccountPoolRef()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EvaluationRouteEvidenceUpdate) SetAttempts(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableAttempts(v *int) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EvaluationRouteEvidenceUpdate) AddAttempts(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetFallbackChain sets the "fallback_chain" field.
func (_u *EvaluationRouteEvidenceUpdate) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetFallbackChain(v)
	return _u
}

// AppendFallbackChain appends value to the "fallback_chain" field.
func (_u *EvaluationRouteEvidenceUpdate) AppendFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AppendFallbackChain(v)
	return _u
}

// SetFinishReason sets the "finish_reason" field.
func (_u *EvaluationRouteEvidenceUpdate) SetFinishReason(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetFinishReason(v)
	return _u
}

// SetNillableFinishReason sets the "finish_reason" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableFinishReason(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetFinishReason(*v)
	}
	return _u
}

// ClearFinishReason clears the value of the "finish_reason" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearFinishReason() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearFinishReason()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) SetInputTokens(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableInputTokens(v *int) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) AddInputTokens(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearInputTokens() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) SetOutputTokens(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableOutputTokens(v *int) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) AddOutputTokens(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearOutputTokens() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) SetTtftMs(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableTtftMs(v *int) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) AddTtftMs(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddTtftMs(v)
	return _u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearTtftMs() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearTtftMs()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) SetLatencyMs(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableLatencyMs(v *int) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) AddLatencyMs(v int) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearLatencyMs() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetBilledAmount sets the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdate) SetBilledAmount(v float64) *EvaluationRouteEvidenceUpdate {
	_u.mutation.ResetBilledAmount()
	_u.mutation.SetBilledAmount(v)
	return _u
}

// SetNillableBilledAmount sets the "billed_amount" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableBilledAmount(v *float64) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetBilledAmount(*v)
	}
	return _u
}

// AddBilledAmount adds value to the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdate) AddBilledAmount(v float64) *EvaluationRouteEvidenceUpdate {
	_u.mutation.AddBilledAmount(v)
	return _u
}

// ClearBilledAmount clears the value of the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearBilledAmount() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearBilledAmount()
	return _u
}

// SetTransportStatus sets the "transport_status" field.
func (_u *EvaluationRouteEvidenceUpdate) SetTransportStatus(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetTransportStatus(v)
	return _u
}

// SetNillableTransportStatus sets the "transport_status" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableTransportStatus(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetTransportStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *EvaluationRouteEvidenceUpdate) SetErrorCode(v string) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableErrorCode(v *string) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearErrorCode() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EvaluationRouteEvidenceUpdate) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdate) SetNillableFinishedAt(v *time.Time) *EvaluationRouteEvidenceUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EvaluationRouteEvidenceUpdate) ClearFinishedAt() *EvaluationRouteEvidenceUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationRouteEvidenceUpdate) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvaluationRouteEvidenceMutation object of the builder.
func (_u *EvaluationRouteEvidenceUpdate) Mutation() *EvaluationRouteEvidenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvaluationRouteEvidenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationRouteEvidenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvaluationRouteEvidenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationRouteEvidenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationRouteEvidenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationrouteevidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationRouteEvidenceUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := evaluationrouteevidence.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResolvedModel(); ok {
		if err := evaluationrouteevidence.ResolvedModelValidator(v); err != nil {
			return &ValidationError{Name: "resolved_model", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.resolved_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := evaluationrouteevidence.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelRef(); ok {
		if err := evaluationrouteevidence.ChannelRefValidator(v); err != nil {
			return &ValidationError{Name: "channel_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.channel_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountPoolRef(); ok {
		if err := evaluationrouteevidence.AccountPoolRefValidator(v); err != nil {
			return &ValidationError{Name: "account_pool_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.account_pool_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := evaluationrouteevidence.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.attempts": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinishReason(); ok {
		if err := evaluationrouteevidence.FinishReasonValidator(v); err != nil {
			return &ValidationError{Name: "finish_reason", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.finish_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := evaluationrouteevidence.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := evaluationrouteevidence.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TtftMs(); ok {
		if err := evaluationrouteevidence.TtftMsValidator(v); err != nil {
			return &ValidationError{Name: "ttft_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.ttft_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LatencyMs(); ok {
		if err := evaluationrouteevidence.LatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "latency_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.latency_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransportStatus(); ok {
		if err := evaluationrouteevidence.TransportStatusValidator(v); err != nil {
			return &ValidationError{Name: "transport_status", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.transport_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := evaluationrouteevidence.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.error_code": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationRouteEvidence.api_key"`)
	}
	return nil
}

func (_u *EvaluationRouteEvidenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationrouteevidence.Table, evaluationrouteevidence.Columns, sqlgraph.NewFieldSpec(evaluationrouteevidence.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedModel(); ok {
		_spec.SetField(evaluationrouteevidence.FieldResolvedModel, field.TypeString, value)
	}
	if _u.mutation.ResolvedModelCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldResolvedModel, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(evaluationrouteevidence.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldChannelRef, field.TypeString, value)
	}
	if _u.mutation.ChannelRefCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldChannelRef, field.TypeString)
	}
	if value, ok := _u.mutation.AccountPoolRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAccountPoolRef, field.TypeString, value)
	}
	if _u.mutation.AccountPoolRefCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldAccountPoolRef, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(evaluationrouteevidence.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FallbackChain(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFallbackChain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFallbackChain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, evaluationrouteevidence.FieldFallbackChain, value)
		})
	}
	if value, ok := _u.mutation.FinishReason(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishReason, field.TypeString, value)
	}
	if _u.mutation.FinishReasonCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldFinishReason, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(evaluationrouteevidence.FieldInputTokens, field.TypeInt, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(evaluationrouteevidence.FieldTtftMs, field.TypeInt, value)
	}
	if _u.mutation.TtftMsCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldTtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.BilledAmount(); ok {
		_spec.SetField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledAmount(); ok {
		_spec.AddField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.BilledAmountCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TransportStatus(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTransportStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(evaluationrouteevidence.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationrouteevidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvaluationRouteEvidenceUpdateOne is the builder for updating a single EvaluationRouteEvidence entity.
type EvaluationRouteEvidenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvaluationRouteEvidenceMutation
}

// SetRequestID sets the "request_id" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetRequestID(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableRequestID(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearRequestID() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetResolvedModel sets the "resolved_model" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetResolvedModel(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetResolvedModel(v)
	return _u
}

// SetNillableResolvedModel sets the "resolved_model" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableResolvedModel(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetResolvedModel(*v)
	}
	return _u
}

// ClearResolvedModel clears the value of the "resolved_model" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearResolvedModel() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearResolvedModel()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetProvider(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableProvider(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearProvider() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetChannelRef sets the "channel_ref" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetChannelRef(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetChannelRef(v)
	return _u
}

// SetNillableChannelRef sets the "channel_ref" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableChannelRef(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetChannelRef(*v)
	}
	return _u
}

// ClearChannelRef clears the value of the "channel_ref" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearChannelRef() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearChannelRef()
	return _u
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetAccountPoolRef(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetAccountPoolRef(v)
	return _u
}

// SetNillableAccountPoolRef sets the "account_pool_ref" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableAccountPoolRef(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetAccountPoolRef(*v)
	}
	return _u
}

// ClearAccountPoolRef clears the value of the "account_pool_ref" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearAccountPoolRef() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearAccountPoolRef()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetAttempts(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableAttempts(v *int) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddAttempts(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetFallbackChain sets the "fallback_chain" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetFallbackChain(v)
	return _u
}

// AppendFallbackChain appends value to the "fallback_chain" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AppendFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AppendFallbackChain(v)
	return _u
}

// SetFinishReason sets the "finish_reason" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetFinishReason(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetFinishReason(v)
	return _u
}

// SetNillableFinishReason sets the "finish_reason" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableFinishReason(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetFinishReason(*v)
	}
	return _u
}

// ClearFinishReason clears the value of the "finish_reason" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearFinishReason() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearFinishReason()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetInputTokens(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableInputTokens(v *int) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddInputTokens(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearInputTokens() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetOutputTokens(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableOutputTokens(v *int) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddOutputTokens(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearOutputTokens() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetTtftMs(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableTtftMs(v *int) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddTtftMs(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddTtftMs(v)
	return _u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearTtftMs() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearTtftMs()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetLatencyMs(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableLatencyMs(v *int) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddLatencyMs(v int) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearLatencyMs() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetBilledAmount sets the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetBilledAmount(v float64) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ResetBilledAmount()
	_u.mutation.SetBilledAmount(v)
	return _u
}

// SetNillableBilledAmount sets the "billed_amount" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableBilledAmount(v *float64) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetBilledAmount(*v)
	}
	return _u
}

// AddBilledAmount adds value to the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdateOne) AddBilledAmount(v float64) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.AddBilledAmount(v)
	return _u
}

// ClearBilledAmount clears the value of the "billed_amount" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearBilledAmount() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearBilledAmount()
	return _u
}

// SetTransportStatus sets the "transport_status" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetTransportStatus(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetTransportStatus(v)
	return _u
}

// SetNillableTransportStatus sets the "transport_status" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableTransportStatus(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetTransportStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetErrorCode(v string) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableErrorCode(v *string) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearErrorCode() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EvaluationRouteEvidenceUpdateOne) SetNillableFinishedAt(v *time.Time) *EvaluationRouteEvidenceUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EvaluationRouteEvidenceUpdateOne) ClearFinishedAt() *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationRouteEvidenceUpdateOne) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvaluationRouteEvidenceMutation object of the builder.
func (_u *EvaluationRouteEvidenceUpdateOne) Mutation() *EvaluationRouteEvidenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the EvaluationRouteEvidenceUpdate builder.
func (_u *EvaluationRouteEvidenceUpdateOne) Where(ps ...predicate.EvaluationRouteEvidence) *EvaluationRouteEvidenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvaluationRouteEvidenceUpdateOne) Select(field string, fields ...string) *EvaluationRouteEvidenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvaluationRouteEvidence entity.
func (_u *EvaluationRouteEvidenceUpdateOne) Save(ctx context.Context) (*EvaluationRouteEvidence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationRouteEvidenceUpdateOne) SaveX(ctx context.Context) *EvaluationRouteEvidence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvaluationRouteEvidenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationRouteEvidenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationRouteEvidenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationrouteevidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationRouteEvidenceUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := evaluationrouteevidence.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResolvedModel(); ok {
		if err := evaluationrouteevidence.ResolvedModelValidator(v); err != nil {
			return &ValidationError{Name: "resolved_model", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.resolved_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := evaluationrouteevidence.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelRef(); ok {
		if err := evaluationrouteevidence.ChannelRefValidator(v); err != nil {
			return &ValidationError{Name: "channel_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.channel_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountPoolRef(); ok {
		if err := evaluationrouteevidence.AccountPoolRefValidator(v); err != nil {
			return &ValidationError{Name: "account_pool_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.account_pool_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := evaluationrouteevidence.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.attempts": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinishReason(); ok {
		if err := evaluationrouteevidence.FinishReasonValidator(v); err != nil {
			return &ValidationError{Name: "finish_reason", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.finish_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := evaluationrouteevidence.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := evaluationrouteevidence.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TtftMs(); ok {
		if err := evaluationrouteevidence.TtftMsValidator(v); err != nil {
			return &ValidationError{Name: "ttft_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.ttft_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LatencyMs(); ok {
		if err := evaluationrouteevidence.LatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "latency_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.latency_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransportStatus(); ok {
		if err := evaluationrouteevidence.TransportStatusValidator(v); err != nil {
			return &ValidationError{Name: "transport_status", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.transport_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := evaluationrouteevidence.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.error_code": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationRouteEvidence.api_key"`)
	}
	return nil
}

func (_u *EvaluationRouteEvidenceUpdateOne) sqlSave(ctx context.Context) (_node *EvaluationRouteEvidence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationrouteevidence.Table, evaluationrouteevidence.Columns, sqlgraph.NewFieldSpec(evaluationrouteevidence.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EvaluationRouteEvidence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationrouteevidence.FieldID)
		for _, f := range fields {
			if !evaluationrouteevidence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evaluationrouteevidence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedModel(); ok {
		_spec.SetField(evaluationrouteevidence.FieldResolvedModel, field.TypeString, value)
	}
	if _u.mutation.ResolvedModelCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldResolvedModel, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(evaluationrouteevidence.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldChannelRef, field.TypeString, value)
	}
	if _u.mutation.ChannelRefCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldChannelRef, field.TypeString)
	}
	if value, ok := _u.mutation.AccountPoolRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAccountPoolRef, field.TypeString, value)
	}
	if _u.mutation.AccountPoolRefCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldAccountPoolRef, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(evaluationrouteevidence.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FallbackChain(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFallbackChain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFallbackChain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, evaluationrouteevidence.FieldFallbackChain, value)
		})
	}
	if value, ok := _u.mutation.FinishReason(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishReason, field.TypeString, value)
	}
	if _u.mutation.FinishReasonCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldFinishReason, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(evaluationrouteevidence.FieldInputTokens, field.TypeInt, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(evaluationrouteevidence.FieldTtftMs, field.TypeInt, value)
	}
	if _u.mutation.TtftMsCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldTtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.BilledAmount(); ok {
		_spec.SetField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledAmount(); ok {
		_spec.AddField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.BilledAmountCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TransportStatus(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTransportStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(evaluationrouteevidence.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(evaluationrouteevidence.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EvaluationRouteEvidence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationrouteevidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
