// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/evaluationcase"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EvaluationCaseUpdate is the builder for updating EvaluationCase entities.
type EvaluationCaseUpdate struct {
	config
	hooks    []Hook
	mutation *EvaluationCaseMutation
}

// Where appends a list predicates to the EvaluationCaseUpdate builder.
func (_u *EvaluationCaseUpdate) Where(ps ...predicate.EvaluationCase) *EvaluationCaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the EvaluationCaseMutation object of the builder.
func (_u *EvaluationCaseUpdate) Mutation() *EvaluationCaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvaluationCaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationCaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvaluationCaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationCaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationCaseUpdate) check() error {
	if _u.mutation.DatasetVersionCleared() && len(_u.mutation.DatasetVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationCase.dataset_version"`)
	}
	return nil
}

func (_u *EvaluationCaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationcase.Table, evaluationcase.Columns, sqlgraph.NewFieldSpec(evaluationcase.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PromptSpecCleared() {
		_spec.ClearField(evaluationcase.FieldPromptSpec, field.TypeJSON)
	}
	if _u.mutation.ExpectedSpecCleared() {
		_spec.ClearField(evaluationcase.FieldExpectedSpec, field.TypeJSON)
	}
	if _u.mutation.EncryptedSpecCleared() {
		_spec.ClearField(evaluationcase.FieldEncryptedSpec, field.TypeString)
	}
	if _u.mutation.QualityDimensionCleared() {
		_spec.ClearField(evaluationcase.FieldQualityDimension, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationcase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvaluationCaseUpdateOne is the builder for updating a single EvaluationCase entity.
type EvaluationCaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvaluationCaseMutation
}

// Mutation returns the EvaluationCaseMutation object of the builder.
func (_u *EvaluationCaseUpdateOne) Mutation() *EvaluationCaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the EvaluationCaseUpdate builder.
func (_u *EvaluationCaseUpdateOne) Where(ps ...predicate.EvaluationCase) *EvaluationCaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvaluationCaseUpdateOne) Select(field string, fields ...string) *EvaluationCaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvaluationCase entity.
func (_u *EvaluationCaseUpdateOne) Save(ctx context.Context) (*EvaluationCase, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationCaseUpdateOne) SaveX(ctx context.Context) *EvaluationCase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvaluationCaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationCaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationCaseUpdateOne) check() error {
	if _u.mutation.DatasetVersionCleared() && len(_u.mutation.DatasetVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationCase.dataset_version"`)
	}
	return nil
}

func (_u *EvaluationCaseUpdateOne) sqlSave(ctx context.Context) (_node *EvaluationCase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationcase.Table, evaluationcase.Columns, sqlgraph.NewFieldSpec(evaluationcase.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EvaluationCase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationcase.FieldID)
		for _, f := range fields {
			if !evaluationcase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evaluationcase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PromptSpecCleared() {
		_spec.ClearField(evaluationcase.FieldPromptSpec, field.TypeJSON)
	}
	if _u.mutation.ExpectedSpecCleared() {
		_spec.ClearField(evaluationcase.FieldExpectedSpec, field.TypeJSON)
	}
	if _u.mutation.EncryptedSpecCleared() {
		_spec.ClearField(evaluationcase.FieldEncryptedSpec, field.TypeString)
	}
	if _u.mutation.QualityDimensionCleared() {
		_spec.ClearField(evaluationcase.FieldQualityDimension, field.TypeString)
	}
	_node = &EvaluationCase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationcase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
