// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EvaluationRunUpdate is the builder for updating EvaluationRun entities.
type EvaluationRunUpdate struct {
	config
	hooks    []Hook
	mutation *EvaluationRunMutation
}

// Where appends a list predicates to the EvaluationRunUpdate builder.
func (_u *EvaluationRunUpdate) Where(ps ...predicate.EvaluationRun) *EvaluationRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EvaluationRunUpdate) SetStatus(v string) *EvaluationRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EvaluationRunUpdate) SetNillableStatus(v *string) *EvaluationRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *EvaluationRunUpdate) SetReservedCost(v float64) *EvaluationRunUpdate {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *EvaluationRunUpdate) SetNillableReservedCost(v *float64) *EvaluationRunUpdate {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *EvaluationRunUpdate) AddReservedCost(v float64) *EvaluationRunUpdate {
	_u.mutation.AddReservedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *EvaluationRunUpdate) SetActualCost(v float64) *EvaluationRunUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *EvaluationRunUpdate) SetNillableActualCost(v *float64) *EvaluationRunUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *EvaluationRunUpdate) AddActualCost(v float64) *EvaluationRunUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EvaluationRunUpdate) SetStartedAt(v time.Time) *EvaluationRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EvaluationRunUpdate) SetNillableStartedAt(v *time.Time) *EvaluationRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EvaluationRunUpdate) ClearStartedAt() *EvaluationRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EvaluationRunUpdate) SetFinishedAt(v time.Time) *EvaluationRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EvaluationRunUpdate) SetNillableFinishedAt(v *time.Time) *EvaluationRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EvaluationRunUpdate) ClearFinishedAt() *EvaluationRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationRunUpdate) SetUpdatedAt(v time.Time) *EvaluationRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvaluationRunMutation object of the builder.
func (_u *EvaluationRunUpdate) Mutation() *EvaluationRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvaluationRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvaluationRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := evaluationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EvaluationRun.status": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationRun.plan"`)
	}
	return nil
}

func (_u *EvaluationRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationrun.Table, evaluationrun.Columns, sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(evaluationrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(evaluationrun.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(evaluationrun.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(evaluationrun.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(evaluationrun.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(evaluationrun.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(evaluationrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(evaluationrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(evaluationrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(evaluationrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvaluationRunUpdateOne is the builder for updating a single EvaluationRun entity.
type EvaluationRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvaluationRunMutation
}

// SetStatus sets the "status" field.
func (_u *EvaluationRunUpdateOne) SetStatus(v string) *EvaluationRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EvaluationRunUpdateOne) SetNillableStatus(v *string) *EvaluationRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *EvaluationRunUpdateOne) SetReservedCost(v float64) *EvaluationRunUpdateOne {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *EvaluationRunUpdateOne) SetNillableReservedCost(v *float64) *EvaluationRunUpdateOne {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *EvaluationRunUpdateOne) AddReservedCost(v float64) *EvaluationRunUpdateOne {
	_u.mutation.AddReservedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *EvaluationRunUpdateOne) SetActualCost(v float64) *EvaluationRunUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *EvaluationRunUpdateOne) SetNillableActualCost(v *float64) *EvaluationRunUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *EvaluationRunUpdateOne) AddActualCost(v float64) *EvaluationRunUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EvaluationRunUpdateOne) SetStartedAt(v time.Time) *EvaluationRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EvaluationRunUpdateOne) SetNillableStartedAt(v *time.Time) *EvaluationRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EvaluationRunUpdateOne) ClearStartedAt() *EvaluationRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EvaluationRunUpdateOne) SetFinishedAt(v time.Time) *EvaluationRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EvaluationRunUpdateOne) SetNillableFinishedAt(v *time.Time) *EvaluationRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EvaluationRunUpdateOne) ClearFinishedAt() *EvaluationRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationRunUpdateOne) SetUpdatedAt(v time.Time) *EvaluationRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvaluationRunMutation object of the builder.
func (_u *EvaluationRunUpdateOne) Mutation() *EvaluationRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the EvaluationRunUpdate builder.
func (_u *EvaluationRunUpdateOne) Where(ps ...predicate.EvaluationRun) *EvaluationRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvaluationRunUpdateOne) Select(field string, fields ...string) *EvaluationRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvaluationRun entity.
func (_u *EvaluationRunUpdateOne) Save(ctx context.Context) (*EvaluationRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationRunUpdateOne) SaveX(ctx context.Context) *EvaluationRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvaluationRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := evaluationrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EvaluationRun.status": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationRun.plan"`)
	}
	return nil
}

func (_u *EvaluationRunUpdateOne) sqlSave(ctx context.Context) (_node *EvaluationRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationrun.Table, evaluationrun.Columns, sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EvaluationRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationrun.FieldID)
		for _, f := range fields {
			if !evaluationrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evaluationrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(evaluationrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(evaluationrun.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(evaluationrun.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(evaluationrun.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(evaluationrun.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(evaluationrun.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(evaluationrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(evaluationrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(evaluationrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(evaluationrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationrun.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EvaluationRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
