// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EvaluationRunDelete is the builder for deleting a EvaluationRun entity.
type EvaluationRunDelete struct {
	config
	hooks    []Hook
	mutation *EvaluationRunMutation
}

// Where appends a list predicates to the EvaluationRunDelete builder.
func (_d *EvaluationRunDelete) Where(ps ...predicate.EvaluationRun) *EvaluationRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EvaluationRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EvaluationRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EvaluationRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(evaluationrun.Table, sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EvaluationRunDeleteOne is the builder for deleting a single EvaluationRun entity.
type EvaluationRunDeleteOne struct {
	_d *EvaluationRunDelete
}

// Where appends a list predicates to the EvaluationRunDelete builder.
func (_d *EvaluationRunDeleteOne) Where(ps ...predicate.EvaluationRun) *EvaluationRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EvaluationRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{evaluationrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EvaluationRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
