// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/evaluationcase"
	"github.com/Wei-Shaw/sub2api/ent/evaluationdatasetversion"
	"github.com/Wei-Shaw/sub2api/ent/evaluationplan"
	"github.com/google/uuid"
)

// EvaluationDatasetVersionCreate is the builder for creating a EvaluationDatasetVersion entity.
type EvaluationDatasetVersionCreate struct {
	config
	mutation *EvaluationDatasetVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDatasetKey sets the "dataset_key" field.
func (_c *EvaluationDatasetVersionCreate) SetDatasetKey(v string) *EvaluationDatasetVersionCreate {
	_c.mutation.SetDatasetKey(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *EvaluationDatasetVersionCreate) SetVersion(v string) *EvaluationDatasetVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (_c *EvaluationDatasetVersionCreate) SetManifestSha256(v string) *EvaluationDatasetVersionCreate {
	_c.mutation.SetManifestSha256(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *EvaluationDatasetVersionCreate) SetSourceType(v string) *EvaluationDatasetVersionCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EvaluationDatasetVersionCreate) SetStatus(v string) *EvaluationDatasetVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillableStatus(v *string) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EvaluationDatasetVersionCreate) SetCreatedBy(v int64) *EvaluationDatasetVersionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *EvaluationDatasetVersionCreate) SetPublishedAt(v time.Time) *EvaluationDatasetVersionCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillablePublishedAt(v *time.Time) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetRetiredAt sets the "retired_at" field.
func (_c *EvaluationDatasetVersionCreate) SetRetiredAt(v time.Time) *EvaluationDatasetVersionCreate {
	_c.mutation.SetRetiredAt(v)
	return _c
}

// SetNillableRetiredAt sets the "retired_at" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillableRetiredAt(v *time.Time) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetRetiredAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EvaluationDatasetVersionCreate) SetCreatedAt(v time.Time) *EvaluationDatasetVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillableCreatedAt(v *time.Time) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EvaluationDatasetVersionCreate) SetUpdatedAt(v time.Time) *EvaluationDatasetVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillableUpdatedAt(v *time.Time) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EvaluationDatasetVersionCreate) SetID(v uuid.UUID) *EvaluationDatasetVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EvaluationDatasetVersionCreate) SetNillableID(v *uuid.UUID) *EvaluationDatasetVersionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddCaseIDs adds the "cases" edge to the EvaluationCase entity by IDs.
func (_c *EvaluationDatasetVersionCreate) AddCaseIDs(ids ...uuid.UUID) *EvaluationDatasetVersionCreate {
	_c.mutation.AddCaseIDs(ids...)
	return _c
}

// AddCases adds the "cases" edges to the EvaluationCase entity.
func (_c *EvaluationDatasetVersionCreate) AddCases(v ...*EvaluationCase) *EvaluationDatasetVersionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCaseIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the EvaluationPlan entity by IDs.
func (_c *EvaluationDatasetVersionCreate) AddPlanIDs(ids ...uuid.UUID) *EvaluationDatasetVersionCreate {
	_c.mutation.AddPlanIDs(ids...)
	return _c
}

// AddPlans adds the "plans" edges to the EvaluationPlan entity.
func (_c *EvaluationDatasetVersionCreate) AddPlans(v ...*EvaluationPlan) *EvaluationDatasetVersionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlanIDs(ids...)
}

// Mutation returns the EvaluationDatasetVersionMutation object of the builder.
func (_c *EvaluationDatasetVersionCreate) Mutation() *EvaluationDatasetVersionMutation {
	return _c.mutation
}

// Save creates the EvaluationDatasetVersion in the database.
func (_c *EvaluationDatasetVersionCreate) Save(ctx context.Context) (*EvaluationDatasetVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EvaluationDatasetVersionCreate) SaveX(ctx context.Context) *EvaluationDatasetVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvaluationDatasetVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvaluationDatasetVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EvaluationDatasetVersionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := evaluationdatasetversion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := evaluationdatasetversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := evaluationdatasetversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := evaluationdatasetversion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EvaluationDatasetVersionCreate) check() error {
	if _, ok := _c.mutation.DatasetKey(); !ok {
		return &ValidationError{Name: "dataset_key", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.dataset_key"`)}
	}
	if v, ok := _c.mutation.DatasetKey(); ok {
		if err := evaluationdatasetversion.DatasetKeyValidator(v); err != nil {
			return &ValidationError{Name: "dataset_key", err: fmt.Errorf(`ent: validator failed for field "EvaluationDatasetVersion.dataset_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := evaluationdatasetversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EvaluationDatasetVersion.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManifestSha256(); !ok {
		return &ValidationError{Name: "manifest_sha256", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.manifest_sha256"`)}
	}
	if v, ok := _c.mutation.ManifestSha256(); ok {
		if err := evaluationdatasetversion.ManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "EvaluationDatasetVersion.manifest_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := evaluationdatasetversion.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "EvaluationDatasetVersion.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := evaluationdatasetversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EvaluationDatasetVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EvaluationDatasetVersion.updated_at"`)}
	}
	return nil
}

func (_c *EvaluationDatasetVersionCreate) sqlSave(ctx context.Context) (*EvaluationDatasetVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EvaluationDatasetVersionCreate) createSpec() (*EvaluationDatasetVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &EvaluationDatasetVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(evaluationdatasetversion.Table, sqlgraph.NewFieldSpec(evaluationdatasetversion.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DatasetKey(); ok {
		_spec.SetField(evaluationdatasetversion.FieldDatasetKey, field.TypeString, value)
		_node.DatasetKey = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(evaluationdatasetversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ManifestSha256(); ok {
		_spec.SetField(evaluationdatasetversion.FieldManifestSha256, field.TypeString, value)
		_node.ManifestSha256 = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(evaluationdatasetversion.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(evaluationdatasetversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(evaluationdatasetversion.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(evaluationdatasetversion.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.RetiredAt(); ok {
		_spec.SetField(evaluationdatasetversion.FieldRetiredAt, field.TypeTime, value)
		_node.RetiredAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(evaluationdatasetversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationdatasetversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationdatasetversion.CasesTable,
			Columns: []string{evaluationdatasetversion.CasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationcase.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationdatasetversion.PlansTable,
			Columns: []string{evaluationdatasetversion.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EvaluationDatasetVersion.Create().
//		SetDatasetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvaluationDatasetVersionUpsert) {
//			SetDatasetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *EvaluationDatasetVersionCreate) OnConflict(opts ...sql.ConflictOption) *EvaluationDatasetVersionUpsertOne {
	_c.conflict = opts
	return &EvaluationDatasetVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvaluationDatasetVersionCreate) OnConflictColumns(columns ...string) *EvaluationDatasetVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvaluationDatasetVersionUpsertOne{
		create: _c,
	}
}

type (
	// EvaluationDatasetVersionUpsertOne is the builder for "upsert"-ing
	//  one EvaluationDatasetVersion node.
	EvaluationDatasetVersionUpsertOne struct {
		create *EvaluationDatasetVersionCreate
	}

	// EvaluationDatasetVersionUpsert is the "OnConflict" setter.
	EvaluationDatasetVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *EvaluationDatasetVersionUpsert) SetStatus(v string) *EvaluationDatasetVersionUpsert {
	u.Set(evaluationdatasetversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsert) UpdateStatus() *EvaluationDatasetVersionUpsert {
	u.SetExcluded(evaluationdatasetversion.FieldStatus)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *EvaluationDatasetVersionUpsert) SetPublishedAt(v time.Time) *EvaluationDatasetVersionUpsert {
	u.Set(evaluationdatasetversion.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsert) UpdatePublishedAt() *EvaluationDatasetVersionUpsert {
	u.SetExcluded(evaluationdatasetversion.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EvaluationDatasetVersionUpsert) ClearPublishedAt() *EvaluationDatasetVersionUpsert {
	u.SetNull(evaluationdatasetversion.FieldPublishedAt)
	return u
}

// SetRetiredAt sets the "retired_at" field.
func (u *EvaluationDatasetVersionUpsert) SetRetiredAt(v time.Time) *EvaluationDatasetVersionUpsert {
	u.Set(evaluationdatasetversion.FieldRetiredAt, v)
	return u
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsert) UpdateRetiredAt() *EvaluationDatasetVersionUpsert {
	u.SetExcluded(evaluationdatasetversion.FieldRetiredAt)
	return u
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *EvaluationDatasetVersionUpsert) ClearRetiredAt() *EvaluationDatasetVersionUpsert {
	u.SetNull(evaluationdatasetversion.FieldRetiredAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationDatasetVersionUpsert) SetUpdatedAt(v time.Time) *EvaluationDatasetVersionUpsert {
	u.Set(evaluationdatasetversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsert) UpdateUpdatedAt() *EvaluationDatasetVersionUpsert {
	u.SetExcluded(evaluationdatasetversion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evaluationdatasetversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvaluationDatasetVersionUpsertOne) UpdateNewValues() *EvaluationDatasetVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldID)
		}
		if _, exists := u.create.mutation.DatasetKey(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldDatasetKey)
		}
		if _, exists := u.create.mutation.Version(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldVersion)
		}
		if _, exists := u.create.mutation.ManifestSha256(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldManifestSha256)
		}
		if _, exists := u.create.mutation.SourceType(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldSourceType)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(evaluationdatasetversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EvaluationDatasetVersionUpsertOne) Ignore() *EvaluationDatasetVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvaluationDatasetVersionUpsertOne) DoNothing() *EvaluationDatasetVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvaluationDatasetVersionCreate.OnConflict
// documentation for more info.
func (u *EvaluationDatasetVersionUpsertOne) Update(set func(*EvaluationDatasetVersionUpsert)) *EvaluationDatasetVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvaluationDatasetVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *EvaluationDatasetVersionUpsertOne) SetStatus(v string) *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertOne) UpdateStatus() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *EvaluationDatasetVersionUpsertOne) SetPublishedAt(v time.Time) *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertOne) UpdatePublishedAt() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EvaluationDatasetVersionUpsertOne) ClearPublishedAt() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.ClearPublishedAt()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *EvaluationDatasetVersionUpsertOne) SetRetiredAt(v time.Time) *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertOne) UpdateRetiredAt() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *EvaluationDatasetVersionUpsertOne) ClearRetiredAt() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.ClearRetiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationDatasetVersionUpsertOne) SetUpdatedAt(v time.Time) *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertOne) UpdateUpdatedAt() *EvaluationDatasetVersionUpsertOne {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvaluationDatasetVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvaluationDatasetVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvaluationDatasetVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EvaluationDatasetVersionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EvaluationDatasetVersionUpsertOne.ID is not supported by MySQL driver. Use EvaluationDatasetVersionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EvaluationDatasetVersionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EvaluationDatasetVersionCreateBulk is the builder for creating many EvaluationDatasetVersion entities in bulk.
type EvaluationDatasetVersionCreateBulk struct {
	config
	err      error
	builders []*EvaluationDatasetVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the EvaluationDatasetVersion entities in the database.
func (_c *EvaluationDatasetVersionCreateBulk) Save(ctx context.Context) ([]*EvaluationDatasetVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EvaluationDatasetVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EvaluationDatasetVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EvaluationDatasetVersionCreateBulk) SaveX(ctx context.Context) []*EvaluationDatasetVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvaluationDatasetVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvaluationDatasetVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EvaluationDatasetVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvaluationDatasetVersionUpsert) {
//			SetDatasetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *EvaluationDatasetVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *EvaluationDatasetVersionUpsertBulk {
	_c.conflict = opts
	return &EvaluationDatasetVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvaluationDatasetVersionCreateBulk) OnConflictColumns(columns ...string) *EvaluationDatasetVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvaluationDatasetVersionUpsertBulk{
		create: _c,
	}
}

// EvaluationDatasetVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of EvaluationDatasetVersion nodes.
type EvaluationDatasetVersionUpsertBulk struct {
	create *EvaluationDatasetVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evaluationdatasetversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvaluationDatasetVersionUpsertBulk) UpdateNewValues() *EvaluationDatasetVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldID)
			}
			if _, exists := b.mutation.DatasetKey(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldDatasetKey)
			}
			if _, exists := b.mutation.Version(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldVersion)
			}
			if _, exists := b.mutation.ManifestSha256(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldManifestSha256)
			}
			if _, exists := b.mutation.SourceType(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldSourceType)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(evaluationdatasetversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EvaluationDatasetVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EvaluationDatasetVersionUpsertBulk) Ignore() *EvaluationDatasetVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvaluationDatasetVersionUpsertBulk) DoNothing() *EvaluationDatasetVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvaluationDatasetVersionCreateBulk.OnConflict
// documentation for more info.
func (u *EvaluationDatasetVersionUpsertBulk) Update(set func(*EvaluationDatasetVersionUpsert)) *EvaluationDatasetVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvaluationDatasetVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *EvaluationDatasetVersionUpsertBulk) SetStatus(v string) *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertBulk) UpdateStatus() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *EvaluationDatasetVersionUpsertBulk) SetPublishedAt(v time.Time) *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertBulk) UpdatePublishedAt() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EvaluationDatasetVersionUpsertBulk) ClearPublishedAt() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.ClearPublishedAt()
	})
}

// SetRetiredAt sets the "retired_at" field.
func (u *EvaluationDatasetVersionUpsertBulk) SetRetiredAt(v time.Time) *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetRetiredAt(v)
	})
}

// UpdateRetiredAt sets the "retired_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertBulk) UpdateRetiredAt() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateRetiredAt()
	})
}

// ClearRetiredAt clears the value of the "retired_at" field.
func (u *EvaluationDatasetVersionUpsertBulk) ClearRetiredAt() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.ClearRetiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationDatasetVersionUpsertBulk) SetUpdatedAt(v time.Time) *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationDatasetVersionUpsertBulk) UpdateUpdatedAt() *EvaluationDatasetVersionUpsertBulk {
	return u.Update(func(s *EvaluationDatasetVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvaluationDatasetVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EvaluationDatasetVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvaluationDatasetVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvaluationDatasetVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
