// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrouteevidence"
)

// EvaluationRouteEvidenceCreate is the builder for creating a EvaluationRouteEvidence entity.
type EvaluationRouteEvidenceCreate struct {
	config
	mutation *EvaluationRouteEvidenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEvaluationRunID sets the "evaluation_run_id" field.
func (_c *EvaluationRouteEvidenceCreate) SetEvaluationRunID(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetEvaluationRunID(v)
	return _c
}

// SetSampleID sets the "sample_id" field.
func (_c *EvaluationRouteEvidenceCreate) SetSampleID(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetSampleID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *EvaluationRouteEvidenceCreate) SetAPIKeyID(v int64) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *EvaluationRouteEvidenceCreate) SetRequestID(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableRequestID(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *EvaluationRouteEvidenceCreate) SetRequestedModel(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetResolvedModel sets the "resolved_model" field.
func (_c *EvaluationRouteEvidenceCreate) SetResolvedModel(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetResolvedModel(v)
	return _c
}

// SetNillableResolvedModel sets the "resolved_model" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableResolvedModel(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetResolvedModel(*v)
	}
	return _c
}

// SetRouteProfileVersion sets the "route_profile_version" field.
func (_c *EvaluationRouteEvidenceCreate) SetRouteProfileVersion(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetRouteProfileVersion(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *EvaluationRouteEvidenceCreate) SetProvider(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableProvider(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetChannelRef sets the "channel_ref" field.
func (_c *EvaluationRouteEvidenceCreate) SetChannelRef(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetChannelRef(v)
	return _c
}

// SetNillableChannelRef sets the "channel_ref" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableChannelRef(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetChannelRef(*v)
	}
	return _c
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (_c *EvaluationRouteEvidenceCreate) SetAccountPoolRef(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetAccountPoolRef(v)
	return _c
}

// SetNillableAccountPoolRef sets the "account_pool_ref" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableAccountPoolRef(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetAccountPoolRef(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *EvaluationRouteEvidenceCreate) SetRegion(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EvaluationRouteEvidenceCreate) SetAttempts(v int) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableAttempts(v *int) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetFallbackChain sets the "fallback_chain" field.
func (_c *EvaluationRouteEvidenceCreate) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetFallbackChain(v)
	return _c
}

// SetFinishReason sets the "finish_reason" field.
func (_c *EvaluationRouteEvidenceCreate) SetFinishReason(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetFinishReason(v)
	return _c
}

// SetNillableFinishReason sets the "finish_reason" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableFinishReason(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetFinishReason(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *EvaluationRouteEvidenceCreate) SetInputTokens(v int) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableInputTokens(v *int) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *EvaluationRouteEvidenceCreate) SetOutputTokens(v int) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableOutputTokens(v *int) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetTtftMs sets the "ttft_ms" field.
func (_c *EvaluationRouteEvidenceCreate) SetTtftMs(v int) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetTtftMs(v)
	return _c
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableTtftMs(v *int) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetTtftMs(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *EvaluationRouteEvidenceCreate) SetLatencyMs(v int) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableLatencyMs(v *int) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetBilledAmount sets the "billed_amount" field.
func (_c *EvaluationRouteEvidenceCreate) SetBilledAmount(v float64) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetBilledAmount(v)
	return _c
}

// SetNillableBilledAmount sets the "billed_amount" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableBilledAmount(v *float64) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetBilledAmount(*v)
	}
	return _c
}

// SetTransportStatus sets the "transport_status" field.
func (_c *EvaluationRouteEvidenceCreate) SetTransportStatus(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetTransportStatus(v)
	return _c
}

// SetNillableTransportStatus sets the "transport_status" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableTransportStatus(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetTransportStatus(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *EvaluationRouteEvidenceCreate) SetErrorCode(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableErrorCode(v *string) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *EvaluationRouteEvidenceCreate) SetStartedAt(v time.Time) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *EvaluationRouteEvidenceCreate) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableFinishedAt(v *time.Time) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EvaluationRouteEvidenceCreate) SetCreatedAt(v time.Time) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableCreatedAt(v *time.Time) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EvaluationRouteEvidenceCreate) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EvaluationRouteEvidenceCreate) SetNillableUpdatedAt(v *time.Time) *EvaluationRouteEvidenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EvaluationRouteEvidenceCreate) SetID(v string) *EvaluationRouteEvidenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *EvaluationRouteEvidenceCreate) SetAPIKey(v *APIKey) *EvaluationRouteEvidenceCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the EvaluationRouteEvidenceMutation object of the builder.
func (_c *EvaluationRouteEvidenceCreate) Mutation() *EvaluationRouteEvidenceMutation {
	return _c.mutation
}

// Save creates the EvaluationRouteEvidence in the database.
func (_c *EvaluationRouteEvidenceCreate) Save(ctx context.Context) (*EvaluationRouteEvidence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EvaluationRouteEvidenceCreate) SaveX(ctx context.Context) *EvaluationRouteEvidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvaluationRouteEvidenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvaluationRouteEvidenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EvaluationRouteEvidenceCreate) defaults() {
	if _, ok := _c.mutation.Attempts(); !ok {
		v := evaluationrouteevidence.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.TransportStatus(); !ok {
		v := evaluationrouteevidence.DefaultTransportStatus
		_c.mutation.SetTransportStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := evaluationrouteevidence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := evaluationrouteevidence.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EvaluationRouteEvidenceCreate) check() error {
	if _, ok := _c.mutation.EvaluationRunID(); !ok {
		return &ValidationError{Name: "evaluation_run_id", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.evaluation_run_id"`)}
	}
	if _, ok := _c.mutation.SampleID(); !ok {
		return &ValidationError{Name: "sample_id", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.sample_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.api_key_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := evaluationrouteevidence.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.requested_model"`)}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := evaluationrouteevidence.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.requested_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResolvedModel(); ok {
		if err := evaluationrouteevidence.ResolvedModelValidator(v); err != nil {
			return &ValidationError{Name: "resolved_model", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.resolved_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RouteProfileVersion(); !ok {
		return &ValidationError{Name: "route_profile_version", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.route_profile_version"`)}
	}
	if v, ok := _c.mutation.RouteProfileVersion(); ok {
		if err := evaluationrouteevidence.RouteProfileVersionValidator(v); err != nil {
			return &ValidationError{Name: "route_profile_version", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.route_profile_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := evaluationrouteevidence.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ChannelRef(); ok {
		if err := evaluationrouteevidence.ChannelRefValidator(v); err != nil {
			return &ValidationError{Name: "channel_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.channel_ref": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AccountPoolRef(); ok {
		if err := evaluationrouteevidence.AccountPoolRefValidator(v); err != nil {
			return &ValidationError{Name: "account_pool_ref", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.account_pool_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := evaluationrouteevidence.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := evaluationrouteevidence.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.attempts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FallbackChain(); !ok {
		return &ValidationError{Name: "fallback_chain", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.fallback_chain"`)}
	}
	if v, ok := _c.mutation.FinishReason(); ok {
		if err := evaluationrouteevidence.FinishReasonValidator(v); err != nil {
			return &ValidationError{Name: "finish_reason", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.finish_reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InputTokens(); ok {
		if err := evaluationrouteevidence.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.input_tokens": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OutputTokens(); ok {
		if err := evaluationrouteevidence.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.output_tokens": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TtftMs(); ok {
		if err := evaluationrouteevidence.TtftMsValidator(v); err != nil {
			return &ValidationError{Name: "ttft_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.ttft_ms": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LatencyMs(); ok {
		if err := evaluationrouteevidence.LatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "latency_ms", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.latency_ms": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TransportStatus(); !ok {
		return &ValidationError{Name: "transport_status", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.transport_status"`)}
	}
	if v, ok := _c.mutation.TransportStatus(); ok {
		if err := evaluationrouteevidence.TransportStatusValidator(v); err != nil {
			return &ValidationError{Name: "transport_status", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.transport_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := evaluationrouteevidence.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.started_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EvaluationRouteEvidence.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := evaluationrouteevidence.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EvaluationRouteEvidence.id": %w`, err)}
		}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "EvaluationRouteEvidence.api_key"`)}
	}
	return nil
}

func (_c *EvaluationRouteEvidenceCreate) sqlSave(ctx context.Context) (*EvaluationRouteEvidence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EvaluationRouteEvidence.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EvaluationRouteEvidenceCreate) createSpec() (*EvaluationRouteEvidence, *sqlgraph.CreateSpec) {
	var (
		_node = &EvaluationRouteEvidence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(evaluationrouteevidence.Table, sqlgraph.NewFieldSpec(evaluationrouteevidence.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EvaluationRunID(); ok {
		_spec.SetField(evaluationrouteevidence.FieldEvaluationRunID, field.TypeString, value)
		_node.EvaluationRunID = value
	}
	if value, ok := _c.mutation.SampleID(); ok {
		_spec.SetField(evaluationrouteevidence.FieldSampleID, field.TypeString, value)
		_node.SampleID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.ResolvedModel(); ok {
		_spec.SetField(evaluationrouteevidence.FieldResolvedModel, field.TypeString, value)
		_node.ResolvedModel = &value
	}
	if value, ok := _c.mutation.RouteProfileVersion(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRouteProfileVersion, field.TypeString, value)
		_node.RouteProfileVersion = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(evaluationrouteevidence.FieldProvider, field.TypeString, value)
		_node.Provider = &value
	}
	if value, ok := _c.mutation.ChannelRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldChannelRef, field.TypeString, value)
		_node.ChannelRef = &value
	}
	if value, ok := _c.mutation.AccountPoolRef(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAccountPoolRef, field.TypeString, value)
		_node.AccountPoolRef = &value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(evaluationrouteevidence.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(evaluationrouteevidence.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.FallbackChain(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFallbackChain, field.TypeJSON, value)
		_node.FallbackChain = value
	}
	if value, ok := _c.mutation.FinishReason(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishReason, field.TypeString, value)
		_node.FinishReason = &value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = &value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(evaluationrouteevidence.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = &value
	}
	if value, ok := _c.mutation.TtftMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTtftMs, field.TypeInt, value)
		_node.TtftMs = &value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(evaluationrouteevidence.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.BilledAmount(); ok {
		_spec.SetField(evaluationrouteevidence.FieldBilledAmount, field.TypeFloat64, value)
		_node.BilledAmount = &value
	}
	if value, ok := _c.mutation.TransportStatus(); ok {
		_spec.SetField(evaluationrouteevidence.FieldTransportStatus, field.TypeString, value)
		_node.TransportStatus = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(evaluationrouteevidence.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationrouteevidence.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationrouteevidence.APIKeyTable,
			Columns: []string{evaluationrouteevidence.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EvaluationRouteEvidence.Create().
//		SetEvaluationRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvaluationRouteEvidenceUpsert) {
//			SetEvaluationRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *EvaluationRouteEvidenceCreate) OnConflict(opts ...sql.ConflictOption) *EvaluationRouteEvidenceUpsertOne {
	_c.conflict = opts
	return &EvaluationRouteEvidenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvaluationRouteEvidenceCreate) OnConflictColumns(columns ...string) *EvaluationRouteEvidenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvaluationRouteEvidenceUpsertOne{
		create: _c,
	}
}

type (
	// EvaluationRouteEvidenceUpsertOne is the builder for "upsert"-ing
	//  one EvaluationRouteEvidence node.
	EvaluationRouteEvidenceUpsertOne struct {
		create *EvaluationRouteEvidenceCreate
	}

	// EvaluationRouteEvidenceUpsert is the "OnConflict" setter.
	EvaluationRouteEvidenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *EvaluationRouteEvidenceUpsert) SetRequestID(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateRequestID() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EvaluationRouteEvidenceUpsert) ClearRequestID() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldRequestID)
	return u
}

// SetResolvedModel sets the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsert) SetResolvedModel(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldResolvedModel, v)
	return u
}

// UpdateResolvedModel sets the "resolved_model" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateResolvedModel() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldResolvedModel)
	return u
}

// ClearResolvedModel clears the value of the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsert) ClearResolvedModel() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldResolvedModel)
	return u
}

// SetProvider sets the "provider" field.
func (u *EvaluationRouteEvidenceUpsert) SetProvider(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateProvider() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *EvaluationRouteEvidenceUpsert) ClearProvider() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldProvider)
	return u
}

// SetChannelRef sets the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsert) SetChannelRef(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldChannelRef, v)
	return u
}

// UpdateChannelRef sets the "channel_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateChannelRef() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldChannelRef)
	return u
}

// ClearChannelRef clears the value of the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsert) ClearChannelRef() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldChannelRef)
	return u
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsert) SetAccountPoolRef(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldAccountPoolRef, v)
	return u
}

// UpdateAccountPoolRef sets the "account_pool_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateAccountPoolRef() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldAccountPoolRef)
	return u
}

// ClearAccountPoolRef clears the value of the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsert) ClearAccountPoolRef() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldAccountPoolRef)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *EvaluationRouteEvidenceUpsert) SetAttempts(v int) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateAttempts() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *EvaluationRouteEvidenceUpsert) AddAttempts(v int) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldAttempts, v)
	return u
}

// SetFallbackChain sets the "fallback_chain" field.
func (u *EvaluationRouteEvidenceUpsert) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldFallbackChain, v)
	return u
}

// UpdateFallbackChain sets the "fallback_chain" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateFallbackChain() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldFallbackChain)
	return u
}

// SetFinishReason sets the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsert) SetFinishReason(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldFinishReason, v)
	return u
}

// UpdateFinishReason sets the "finish_reason" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateFinishReason() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldFinishReason)
	return u
}

// ClearFinishReason clears the value of the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsert) ClearFinishReason() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldFinishReason)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) SetInputTokens(v int) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateInputTokens() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) AddInputTokens(v int) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldInputTokens, v)
	return u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) ClearInputTokens() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldInputTokens)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) SetOutputTokens(v int) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateOutputTokens() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) AddOutputTokens(v int) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldOutputTokens, v)
	return u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsert) ClearOutputTokens() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldOutputTokens)
	return u
}

// SetTtftMs sets the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsert) SetTtftMs(v int) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldTtftMs, v)
	return u
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateTtftMs() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldTtftMs)
	return u
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsert) AddTtftMs(v int) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldTtftMs, v)
	return u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsert) ClearTtftMs() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldTtftMs)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsert) SetLatencyMs(v int) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateLatencyMs() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsert) AddLatencyMs(v int) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsert) ClearLatencyMs() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldLatencyMs)
	return u
}

// SetBilledAmount sets the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsert) SetBilledAmount(v float64) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldBilledAmount, v)
	return u
}

// UpdateBilledAmount sets the "billed_amount" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateBilledAmount() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldBilledAmount)
	return u
}

// AddBilledAmount adds v to the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsert) AddBilledAmount(v float64) *EvaluationRouteEvidenceUpsert {
	u.Add(evaluationrouteevidence.FieldBilledAmount, v)
	return u
}

// ClearBilledAmount clears the value of the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsert) ClearBilledAmount() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldBilledAmount)
	return u
}

// SetTransportStatus sets the "transport_status" field.
func (u *EvaluationRouteEvidenceUpsert) SetTransportStatus(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldTransportStatus, v)
	return u
}

// UpdateTransportStatus sets the "transport_status" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateTransportStatus() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldTransportStatus)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *EvaluationRouteEvidenceUpsert) SetErrorCode(v string) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateErrorCode() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *EvaluationRouteEvidenceUpsert) ClearErrorCode() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldErrorCode)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsert) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateFinishedAt() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsert) ClearFinishedAt() *EvaluationRouteEvidenceUpsert {
	u.SetNull(evaluationrouteevidence.FieldFinishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationRouteEvidenceUpsert) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceUpsert {
	u.Set(evaluationrouteevidence.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsert) UpdateUpdatedAt() *EvaluationRouteEvidenceUpsert {
	u.SetExcluded(evaluationrouteevidence.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evaluationrouteevidence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvaluationRouteEvidenceUpsertOne) UpdateNewValues() *EvaluationRouteEvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldID)
		}
		if _, exists := u.create.mutation.EvaluationRunID(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldEvaluationRunID)
		}
		if _, exists := u.create.mutation.SampleID(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldSampleID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.RequestedModel(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldRequestedModel)
		}
		if _, exists := u.create.mutation.RouteProfileVersion(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldRouteProfileVersion)
		}
		if _, exists := u.create.mutation.Region(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldRegion)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldStartedAt)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(evaluationrouteevidence.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EvaluationRouteEvidenceUpsertOne) Ignore() *EvaluationRouteEvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvaluationRouteEvidenceUpsertOne) DoNothing() *EvaluationRouteEvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvaluationRouteEvidenceCreate.OnConflict
// documentation for more info.
func (u *EvaluationRouteEvidenceUpsertOne) Update(set func(*EvaluationRouteEvidenceUpsert)) *EvaluationRouteEvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvaluationRouteEvidenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetRequestID(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateRequestID() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearRequestID() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearRequestID()
	})
}

// SetResolvedModel sets the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetResolvedModel(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetResolvedModel(v)
	})
}

// UpdateResolvedModel sets the "resolved_model" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateResolvedModel() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateResolvedModel()
	})
}

// ClearResolvedModel clears the value of the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearResolvedModel() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearResolvedModel()
	})
}

// SetProvider sets the "provider" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetProvider(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateProvider() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearProvider() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearProvider()
	})
}

// SetChannelRef sets the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetChannelRef(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetChannelRef(v)
	})
}

// UpdateChannelRef sets the "channel_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateChannelRef() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateChannelRef()
	})
}

// ClearChannelRef clears the value of the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearChannelRef() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearChannelRef()
	})
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetAccountPoolRef(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetAccountPoolRef(v)
	})
}

// UpdateAccountPoolRef sets the "account_pool_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateAccountPoolRef() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateAccountPoolRef()
	})
}

// ClearAccountPoolRef clears the value of the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearAccountPoolRef() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearAccountPoolRef()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetAttempts(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddAttempts(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateAttempts() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateAttempts()
	})
}

// SetFallbackChain sets the "fallback_chain" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFallbackChain(v)
	})
}

// UpdateFallbackChain sets the "fallback_chain" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateFallbackChain() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFallbackChain()
	})
}

// SetFinishReason sets the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetFinishReason(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFinishReason(v)
	})
}

// UpdateFinishReason sets the "finish_reason" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateFinishReason() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFinishReason()
	})
}

// ClearFinishReason clears the value of the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearFinishReason() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearFinishReason()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetInputTokens(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddInputTokens(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateInputTokens() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateInputTokens()
	})
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearInputTokens() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetOutputTokens(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddOutputTokens(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateOutputTokens() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateOutputTokens()
	})
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearOutputTokens() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearOutputTokens()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetTtftMs(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddTtftMs(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateTtftMs() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearTtftMs() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearTtftMs()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetLatencyMs(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddLatencyMs(v int) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateLatencyMs() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearLatencyMs() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearLatencyMs()
	})
}

// SetBilledAmount sets the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetBilledAmount(v float64) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetBilledAmount(v)
	})
}

// AddBilledAmount adds v to the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertOne) AddBilledAmount(v float64) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddBilledAmount(v)
	})
}

// UpdateBilledAmount sets the "billed_amount" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateBilledAmount() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateBilledAmount()
	})
}

// ClearBilledAmount clears the value of the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearBilledAmount() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearBilledAmount()
	})
}

// SetTransportStatus sets the "transport_status" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetTransportStatus(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetTransportStatus(v)
	})
}

// UpdateTransportStatus sets the "transport_status" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateTransportStatus() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateTransportStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetErrorCode(v string) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateErrorCode() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearErrorCode() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearErrorCode()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateFinishedAt() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsertOne) ClearFinishedAt() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationRouteEvidenceUpsertOne) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertOne) UpdateUpdatedAt() *EvaluationRouteEvidenceUpsertOne {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvaluationRouteEvidenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvaluationRouteEvidenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvaluationRouteEvidenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EvaluationRouteEvidenceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EvaluationRouteEvidenceUpsertOne.ID is not supported by MySQL driver. Use EvaluationRouteEvidenceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EvaluationRouteEvidenceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EvaluationRouteEvidenceCreateBulk is the builder for creating many EvaluationRouteEvidence entities in bulk.
type EvaluationRouteEvidenceCreateBulk struct {
	config
	err      error
	builders []*EvaluationRouteEvidenceCreate
	conflict []sql.ConflictOption
}

// Save creates the EvaluationRouteEvidence entities in the database.
func (_c *EvaluationRouteEvidenceCreateBulk) Save(ctx context.Context) ([]*EvaluationRouteEvidence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EvaluationRouteEvidence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EvaluationRouteEvidenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EvaluationRouteEvidenceCreateBulk) SaveX(ctx context.Context) []*EvaluationRouteEvidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvaluationRouteEvidenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvaluationRouteEvidenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EvaluationRouteEvidence.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvaluationRouteEvidenceUpsert) {
//			SetEvaluationRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *EvaluationRouteEvidenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *EvaluationRouteEvidenceUpsertBulk {
	_c.conflict = opts
	return &EvaluationRouteEvidenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvaluationRouteEvidenceCreateBulk) OnConflictColumns(columns ...string) *EvaluationRouteEvidenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvaluationRouteEvidenceUpsertBulk{
		create: _c,
	}
}

// EvaluationRouteEvidenceUpsertBulk is the builder for "upsert"-ing
// a bulk of EvaluationRouteEvidence nodes.
type EvaluationRouteEvidenceUpsertBulk struct {
	create *EvaluationRouteEvidenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evaluationrouteevidence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateNewValues() *EvaluationRouteEvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldID)
			}
			if _, exists := b.mutation.EvaluationRunID(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldEvaluationRunID)
			}
			if _, exists := b.mutation.SampleID(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldSampleID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldAPIKeyID)
			}
			if _, exists := b.mutation.RequestedModel(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldRequestedModel)
			}
			if _, exists := b.mutation.RouteProfileVersion(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldRouteProfileVersion)
			}
			if _, exists := b.mutation.Region(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldRegion)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldStartedAt)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(evaluationrouteevidence.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EvaluationRouteEvidence.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EvaluationRouteEvidenceUpsertBulk) Ignore() *EvaluationRouteEvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvaluationRouteEvidenceUpsertBulk) DoNothing() *EvaluationRouteEvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvaluationRouteEvidenceCreateBulk.OnConflict
// documentation for more info.
func (u *EvaluationRouteEvidenceUpsertBulk) Update(set func(*EvaluationRouteEvidenceUpsert)) *EvaluationRouteEvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvaluationRouteEvidenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetRequestID(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateRequestID() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearRequestID() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearRequestID()
	})
}

// SetResolvedModel sets the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetResolvedModel(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetResolvedModel(v)
	})
}

// UpdateResolvedModel sets the "resolved_model" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateResolvedModel() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateResolvedModel()
	})
}

// ClearResolvedModel clears the value of the "resolved_model" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearResolvedModel() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearResolvedModel()
	})
}

// SetProvider sets the "provider" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetProvider(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateProvider() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearProvider() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearProvider()
	})
}

// SetChannelRef sets the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetChannelRef(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetChannelRef(v)
	})
}

// UpdateChannelRef sets the "channel_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateChannelRef() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateChannelRef()
	})
}

// ClearChannelRef clears the value of the "channel_ref" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearChannelRef() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearChannelRef()
	})
}

// SetAccountPoolRef sets the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetAccountPoolRef(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetAccountPoolRef(v)
	})
}

// UpdateAccountPoolRef sets the "account_pool_ref" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateAccountPoolRef() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateAccountPoolRef()
	})
}

// ClearAccountPoolRef clears the value of the "account_pool_ref" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearAccountPoolRef() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearAccountPoolRef()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetAttempts(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddAttempts(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateAttempts() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateAttempts()
	})
}

// SetFallbackChain sets the "fallback_chain" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetFallbackChain(v []map[string]interface{}) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFallbackChain(v)
	})
}

// UpdateFallbackChain sets the "fallback_chain" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateFallbackChain() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFallbackChain()
	})
}

// SetFinishReason sets the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetFinishReason(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFinishReason(v)
	})
}

// UpdateFinishReason sets the "finish_reason" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateFinishReason() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFinishReason()
	})
}

// ClearFinishReason clears the value of the "finish_reason" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearFinishReason() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearFinishReason()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetInputTokens(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddInputTokens(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateInputTokens() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateInputTokens()
	})
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearInputTokens() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetOutputTokens(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddOutputTokens(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateOutputTokens() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateOutputTokens()
	})
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearOutputTokens() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearOutputTokens()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetTtftMs(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddTtftMs(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateTtftMs() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearTtftMs() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearTtftMs()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetLatencyMs(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddLatencyMs(v int) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateLatencyMs() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearLatencyMs() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearLatencyMs()
	})
}

// SetBilledAmount sets the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetBilledAmount(v float64) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetBilledAmount(v)
	})
}

// AddBilledAmount adds v to the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertBulk) AddBilledAmount(v float64) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.AddBilledAmount(v)
	})
}

// UpdateBilledAmount sets the "billed_amount" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateBilledAmount() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateBilledAmount()
	})
}

// ClearBilledAmount clears the value of the "billed_amount" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearBilledAmount() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearBilledAmount()
	})
}

// SetTransportStatus sets the "transport_status" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetTransportStatus(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetTransportStatus(v)
	})
}

// UpdateTransportStatus sets the "transport_status" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateTransportStatus() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateTransportStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetErrorCode(v string) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateErrorCode() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearErrorCode() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearErrorCode()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetFinishedAt(v time.Time) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateFinishedAt() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *EvaluationRouteEvidenceUpsertBulk) ClearFinishedAt() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvaluationRouteEvidenceUpsertBulk) SetUpdatedAt(v time.Time) *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvaluationRouteEvidenceUpsertBulk) UpdateUpdatedAt() *EvaluationRouteEvidenceUpsertBulk {
	return u.Update(func(s *EvaluationRouteEvidenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvaluationRouteEvidenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EvaluationRouteEvidenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvaluationRouteEvidenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvaluationRouteEvidenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
