// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/evaluationplan"
	"github.com/Wei-Shaw/sub2api/ent/evaluationrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// EvaluationPlanUpdate is the builder for updating EvaluationPlan entities.
type EvaluationPlanUpdate struct {
	config
	hooks    []Hook
	mutation *EvaluationPlanMutation
}

// Where appends a list predicates to the EvaluationPlanUpdate builder.
func (_u *EvaluationPlanUpdate) Where(ps ...predicate.EvaluationPlan) *EvaluationPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *EvaluationPlanUpdate) SetName(v string) *EvaluationPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableName(v *string) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGatewayAPIKeyID sets the "gateway_api_key_id" field.
func (_u *EvaluationPlanUpdate) SetGatewayAPIKeyID(v int64) *EvaluationPlanUpdate {
	_u.mutation.SetGatewayAPIKeyID(v)
	return _u
}

// SetNillableGatewayAPIKeyID sets the "gateway_api_key_id" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableGatewayAPIKeyID(v *int64) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetGatewayAPIKeyID(*v)
	}
	return _u
}

// ClearGatewayAPIKeyID clears the value of the "gateway_api_key_id" field.
func (_u *EvaluationPlanUpdate) ClearGatewayAPIKeyID() *EvaluationPlanUpdate {
	_u.mutation.ClearGatewayAPIKeyID()
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *EvaluationPlanUpdate) SetTriggerType(v string) *EvaluationPlanUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableTriggerType(v *string) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *EvaluationPlanUpdate) SetCronExpression(v string) *EvaluationPlanUpdate {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableCronExpression(v *string) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *EvaluationPlanUpdate) ClearCronExpression() *EvaluationPlanUpdate {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetModelMatrix sets the "model_matrix" field.
func (_u *EvaluationPlanUpdate) SetModelMatrix(v []map[string]interface{}) *EvaluationPlanUpdate {
	_u.mutation.SetModelMatrix(v)
	return _u
}

// AppendModelMatrix appends value to the "model_matrix" field.
func (_u *EvaluationPlanUpdate) AppendModelMatrix(v []map[string]interface{}) *EvaluationPlanUpdate {
	_u.mutation.AppendModelMatrix(v)
	return _u
}

// SetMaxRunCost sets the "max_run_cost" field.
func (_u *EvaluationPlanUpdate) SetMaxRunCost(v float64) *EvaluationPlanUpdate {
	_u.mutation.ResetMaxRunCost()
	_u.mutation.SetMaxRunCost(v)
	return _u
}

// SetNillableMaxRunCost sets the "max_run_cost" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableMaxRunCost(v *float64) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetMaxRunCost(*v)
	}
	return _u
}

// AddMaxRunCost adds value to the "max_run_cost" field.
func (_u *EvaluationPlanUpdate) AddMaxRunCost(v float64) *EvaluationPlanUpdate {
	_u.mutation.AddMaxRunCost(v)
	return _u
}

// SetDailyCostLimit sets the "daily_cost_limit" field.
func (_u *EvaluationPlanUpdate) SetDailyCostLimit(v float64) *EvaluationPlanUpdate {
	_u.mutation.ResetDailyCostLimit()
	_u.mutation.SetDailyCostLimit(v)
	return _u
}

// SetNillableDailyCostLimit sets the "daily_cost_limit" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableDailyCostLimit(v *float64) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetDailyCostLimit(*v)
	}
	return _u
}

// AddDailyCostLimit adds value to the "daily_cost_limit" field.
func (_u *EvaluationPlanUpdate) AddDailyCostLimit(v float64) *EvaluationPlanUpdate {
	_u.mutation.AddDailyCostLimit(v)
	return _u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_u *EvaluationPlanUpdate) SetMaxConcurrency(v int) *EvaluationPlanUpdate {
	_u.mutation.ResetMaxConcurrency()
	_u.mutation.SetMaxConcurrency(v)
	return _u
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableMaxConcurrency(v *int) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetMaxConcurrency(*v)
	}
	return _u
}

// AddMaxConcurrency adds value to the "max_concurrency" field.
func (_u *EvaluationPlanUpdate) AddMaxConcurrency(v int) *EvaluationPlanUpdate {
	_u.mutation.AddMaxConcurrency(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EvaluationPlanUpdate) SetEnabled(v bool) *EvaluationPlanUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EvaluationPlanUpdate) SetNillableEnabled(v *bool) *EvaluationPlanUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationPlanUpdate) SetUpdatedAt(v time.Time) *EvaluationPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGatewayAPIKey sets the "gateway_api_key" edge to the APIKey entity.
func (_u *EvaluationPlanUpdate) SetGatewayAPIKey(v *APIKey) *EvaluationPlanUpdate {
	return _u.SetGatewayAPIKeyID(v.ID)
}

// AddRunIDs adds the "runs" edge to the EvaluationRun entity by IDs.
func (_u *EvaluationPlanUpdate) AddRunIDs(ids ...uuid.UUID) *EvaluationPlanUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the EvaluationRun entity.
func (_u *EvaluationPlanUpdate) AddRuns(v ...*EvaluationRun) *EvaluationPlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// Mutation returns the EvaluationPlanMutation object of the builder.
func (_u *EvaluationPlanUpdate) Mutation() *EvaluationPlanMutation {
	return _u.mutation
}

// ClearGatewayAPIKey clears the "gateway_api_key" edge to the APIKey entity.
func (_u *EvaluationPlanUpdate) ClearGatewayAPIKey() *EvaluationPlanUpdate {
	_u.mutation.ClearGatewayAPIKey()
	return _u
}

// ClearRuns clears all "runs" edges to the EvaluationRun entity.
func (_u *EvaluationPlanUpdate) ClearRuns() *EvaluationPlanUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to EvaluationRun entities by IDs.
func (_u *EvaluationPlanUpdate) RemoveRunIDs(ids ...uuid.UUID) *EvaluationPlanUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to EvaluationRun entities.
func (_u *EvaluationPlanUpdate) RemoveRuns(v ...*EvaluationRun) *EvaluationPlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvaluationPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvaluationPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := evaluationplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := evaluationplan.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := evaluationplan.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.cron_expression": %w`, err)}
		}
	}
	if _u.mutation.DatasetVersionCleared() && len(_u.mutation.DatasetVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationPlan.dataset_version"`)
	}
	return nil
}

func (_u *EvaluationPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationplan.Table, evaluationplan.Columns, sqlgraph.NewFieldSpec(evaluationplan.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(evaluationplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(evaluationplan.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(evaluationplan.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(evaluationplan.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.ModelMatrix(); ok {
		_spec.SetField(evaluationplan.FieldModelMatrix, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelMatrix(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, evaluationplan.FieldModelMatrix, value)
		})
	}
	if value, ok := _u.mutation.MaxRunCost(); ok {
		_spec.SetField(evaluationplan.FieldMaxRunCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxRunCost(); ok {
		_spec.AddField(evaluationplan.FieldMaxRunCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyCostLimit(); ok {
		_spec.SetField(evaluationplan.FieldDailyCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyCostLimit(); ok {
		_spec.AddField(evaluationplan.FieldDailyCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxConcurrency(); ok {
		_spec.SetField(evaluationplan.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(evaluationplan.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(evaluationplan.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GatewayAPIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationplan.GatewayAPIKeyTable,
			Columns: []string{evaluationplan.GatewayAPIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GatewayAPIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationplan.GatewayAPIKeyTable,
			Columns: []string{evaluationplan.GatewayAPIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvaluationPlanUpdateOne is the builder for updating a single EvaluationPlan entity.
type EvaluationPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvaluationPlanMutation
}

// SetName sets the "name" field.
func (_u *EvaluationPlanUpdateOne) SetName(v string) *EvaluationPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableName(v *string) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGatewayAPIKeyID sets the "gateway_api_key_id" field.
func (_u *EvaluationPlanUpdateOne) SetGatewayAPIKeyID(v int64) *EvaluationPlanUpdateOne {
	_u.mutation.SetGatewayAPIKeyID(v)
	return _u
}

// SetNillableGatewayAPIKeyID sets the "gateway_api_key_id" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableGatewayAPIKeyID(v *int64) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetGatewayAPIKeyID(*v)
	}
	return _u
}

// ClearGatewayAPIKeyID clears the value of the "gateway_api_key_id" field.
func (_u *EvaluationPlanUpdateOne) ClearGatewayAPIKeyID() *EvaluationPlanUpdateOne {
	_u.mutation.ClearGatewayAPIKeyID()
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *EvaluationPlanUpdateOne) SetTriggerType(v string) *EvaluationPlanUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableTriggerType(v *string) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *EvaluationPlanUpdateOne) SetCronExpression(v string) *EvaluationPlanUpdateOne {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableCronExpression(v *string) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *EvaluationPlanUpdateOne) ClearCronExpression() *EvaluationPlanUpdateOne {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetModelMatrix sets the "model_matrix" field.
func (_u *EvaluationPlanUpdateOne) SetModelMatrix(v []map[string]interface{}) *EvaluationPlanUpdateOne {
	_u.mutation.SetModelMatrix(v)
	return _u
}

// AppendModelMatrix appends value to the "model_matrix" field.
func (_u *EvaluationPlanUpdateOne) AppendModelMatrix(v []map[string]interface{}) *EvaluationPlanUpdateOne {
	_u.mutation.AppendModelMatrix(v)
	return _u
}

// SetMaxRunCost sets the "max_run_cost" field.
func (_u *EvaluationPlanUpdateOne) SetMaxRunCost(v float64) *EvaluationPlanUpdateOne {
	_u.mutation.ResetMaxRunCost()
	_u.mutation.SetMaxRunCost(v)
	return _u
}

// SetNillableMaxRunCost sets the "max_run_cost" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableMaxRunCost(v *float64) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetMaxRunCost(*v)
	}
	return _u
}

// AddMaxRunCost adds value to the "max_run_cost" field.
func (_u *EvaluationPlanUpdateOne) AddMaxRunCost(v float64) *EvaluationPlanUpdateOne {
	_u.mutation.AddMaxRunCost(v)
	return _u
}

// SetDailyCostLimit sets the "daily_cost_limit" field.
func (_u *EvaluationPlanUpdateOne) SetDailyCostLimit(v float64) *EvaluationPlanUpdateOne {
	_u.mutation.ResetDailyCostLimit()
	_u.mutation.SetDailyCostLimit(v)
	return _u
}

// SetNillableDailyCostLimit sets the "daily_cost_limit" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableDailyCostLimit(v *float64) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetDailyCostLimit(*v)
	}
	return _u
}

// AddDailyCostLimit adds value to the "daily_cost_limit" field.
func (_u *EvaluationPlanUpdateOne) AddDailyCostLimit(v float64) *EvaluationPlanUpdateOne {
	_u.mutation.AddDailyCostLimit(v)
	return _u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_u *EvaluationPlanUpdateOne) SetMaxConcurrency(v int) *EvaluationPlanUpdateOne {
	_u.mutation.ResetMaxConcurrency()
	_u.mutation.SetMaxConcurrency(v)
	return _u
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableMaxConcurrency(v *int) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetMaxConcurrency(*v)
	}
	return _u
}

// AddMaxConcurrency adds value to the "max_concurrency" field.
func (_u *EvaluationPlanUpdateOne) AddMaxConcurrency(v int) *EvaluationPlanUpdateOne {
	_u.mutation.AddMaxConcurrency(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EvaluationPlanUpdateOne) SetEnabled(v bool) *EvaluationPlanUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EvaluationPlanUpdateOne) SetNillableEnabled(v *bool) *EvaluationPlanUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationPlanUpdateOne) SetUpdatedAt(v time.Time) *EvaluationPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGatewayAPIKey sets the "gateway_api_key" edge to the APIKey entity.
func (_u *EvaluationPlanUpdateOne) SetGatewayAPIKey(v *APIKey) *EvaluationPlanUpdateOne {
	return _u.SetGatewayAPIKeyID(v.ID)
}

// AddRunIDs adds the "runs" edge to the EvaluationRun entity by IDs.
func (_u *EvaluationPlanUpdateOne) AddRunIDs(ids ...uuid.UUID) *EvaluationPlanUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the EvaluationRun entity.
func (_u *EvaluationPlanUpdateOne) AddRuns(v ...*EvaluationRun) *EvaluationPlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// Mutation returns the EvaluationPlanMutation object of the builder.
func (_u *EvaluationPlanUpdateOne) Mutation() *EvaluationPlanMutation {
	return _u.mutation
}

// ClearGatewayAPIKey clears the "gateway_api_key" edge to the APIKey entity.
func (_u *EvaluationPlanUpdateOne) ClearGatewayAPIKey() *EvaluationPlanUpdateOne {
	_u.mutation.ClearGatewayAPIKey()
	return _u
}

// ClearRuns clears all "runs" edges to the EvaluationRun entity.
func (_u *EvaluationPlanUpdateOne) ClearRuns() *EvaluationPlanUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to EvaluationRun entities by IDs.
func (_u *EvaluationPlanUpdateOne) RemoveRunIDs(ids ...uuid.UUID) *EvaluationPlanUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to EvaluationRun entities.
func (_u *EvaluationPlanUpdateOne) RemoveRuns(v ...*EvaluationRun) *EvaluationPlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// Where appends a list predicates to the EvaluationPlanUpdate builder.
func (_u *EvaluationPlanUpdateOne) Where(ps ...predicate.EvaluationPlan) *EvaluationPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvaluationPlanUpdateOne) Select(field string, fields ...string) *EvaluationPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvaluationPlan entity.
func (_u *EvaluationPlanUpdateOne) Save(ctx context.Context) (*EvaluationPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationPlanUpdateOne) SaveX(ctx context.Context) *EvaluationPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvaluationPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := evaluationplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := evaluationplan.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := evaluationplan.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "EvaluationPlan.cron_expression": %w`, err)}
		}
	}
	if _u.mutation.DatasetVersionCleared() && len(_u.mutation.DatasetVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvaluationPlan.dataset_version"`)
	}
	return nil
}

func (_u *EvaluationPlanUpdateOne) sqlSave(ctx context.Context) (_node *EvaluationPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationplan.Table, evaluationplan.Columns, sqlgraph.NewFieldSpec(evaluationplan.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EvaluationPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationplan.FieldID)
		for _, f := range fields {
			if !evaluationplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evaluationplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(evaluationplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(evaluationplan.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(evaluationplan.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(evaluationplan.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.ModelMatrix(); ok {
		_spec.SetField(evaluationplan.FieldModelMatrix, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelMatrix(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, evaluationplan.FieldModelMatrix, value)
		})
	}
	if value, ok := _u.mutation.MaxRunCost(); ok {
		_spec.SetField(evaluationplan.FieldMaxRunCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxRunCost(); ok {
		_spec.AddField(evaluationplan.FieldMaxRunCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyCostLimit(); ok {
		_spec.SetField(evaluationplan.FieldDailyCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyCostLimit(); ok {
		_spec.AddField(evaluationplan.FieldDailyCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxConcurrency(); ok {
		_spec.SetField(evaluationplan.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(evaluationplan.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(evaluationplan.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GatewayAPIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationplan.GatewayAPIKeyTable,
			Columns: []string{evaluationplan.GatewayAPIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GatewayAPIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationplan.GatewayAPIKeyTable,
			Columns: []string{evaluationplan.GatewayAPIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   evaluationplan.RunsTable,
			Columns: []string{evaluationplan.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EvaluationPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
