// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/evaluationcase"
	"github.com/Wei-Shaw/sub2api/ent/evaluationdatasetversion"
	"github.com/google/uuid"
)

// EvaluationCase is the model entity for the EvaluationCase schema.
type EvaluationCase struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DatasetVersionID holds the value of the "dataset_version_id" field.
	DatasetVersionID uuid.UUID `json:"dataset_version_id,omitempty"`
	// CaseKey holds the value of the "case_key" field.
	CaseKey string `json:"case_key,omitempty"`
	// CapabilityDomain holds the value of the "capability_domain" field.
	CapabilityDomain string `json:"capability_domain,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight float64 `json:"weight,omitempty"`
	// SampleCount holds the value of the "sample_count" field.
	SampleCount int `json:"sample_count,omitempty"`
	// PromptSpec holds the value of the "prompt_spec" field.
	PromptSpec map[string]interface{} `json:"prompt_spec,omitempty"`
	// ExpectedSpec holds the value of the "expected_spec" field.
	ExpectedSpec map[string]interface{} `json:"expected_spec,omitempty"`
	// EncryptedSpec holds the value of the "encrypted_spec" field.
	EncryptedSpec *string `json:"encrypted_spec,omitempty"`
	// ExecutionSpec holds the value of the "execution_spec" field.
	ExecutionSpec map[string]interface{} `json:"execution_spec,omitempty"`
	// QualityDimension holds the value of the "quality_dimension" field.
	QualityDimension string `json:"quality_dimension,omitempty"`
	// QualityProbeSpec holds the value of the "quality_probe_spec" field.
	QualityProbeSpec map[string]interface{} `json:"quality_probe_spec,omitempty"`
	// GraderID holds the value of the "grader_id" field.
	GraderID string `json:"grader_id,omitempty"`
	// GraderVersion holds the value of the "grader_version" field.
	GraderVersion string `json:"grader_version,omitempty"`
	// ContentSha256 holds the value of the "content_sha256" field.
	ContentSha256 string `json:"content_sha256,omitempty"`
	// Confidentiality holds the value of the "confidentiality" field.
	Confidentiality string `json:"confidentiality,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EvaluationCaseQuery when eager-loading is set.
	Edges        EvaluationCaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EvaluationCaseEdges holds the relations/edges for other nodes in the graph.
type EvaluationCaseEdges struct {
	// DatasetVersion holds the value of the dataset_version edge.
	DatasetVersion *EvaluationDatasetVersion `json:"dataset_version,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DatasetVersionOrErr returns the DatasetVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EvaluationCaseEdges) DatasetVersionOrErr() (*EvaluationDatasetVersion, error) {
	if e.DatasetVersion != nil {
		return e.DatasetVersion, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: evaluationdatasetversion.Label}
	}
	return nil, &NotLoadedError{edge: "dataset_version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EvaluationCase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case evaluationcase.FieldPromptSpec, evaluationcase.FieldExpectedSpec, evaluationcase.FieldExecutionSpec, evaluationcase.FieldQualityProbeSpec:
			values[i] = new([]byte)
		case evaluationcase.FieldWeight, evaluationcase.FieldEstimatedCost:
			values[i] = new(sql.NullFloat64)
		case evaluationcase.FieldSampleCount:
			values[i] = new(sql.NullInt64)
		case evaluationcase.FieldCaseKey, evaluationcase.FieldCapabilityDomain, evaluationcase.FieldPriority, evaluationcase.FieldEncryptedSpec, evaluationcase.FieldQualityDimension, evaluationcase.FieldGraderID, evaluationcase.FieldGraderVersion, evaluationcase.FieldContentSha256, evaluationcase.FieldConfidentiality:
			values[i] = new(sql.NullString)
		case evaluationcase.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case evaluationcase.FieldID, evaluationcase.FieldDatasetVersionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EvaluationCase fields.
func (_m *EvaluationCase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case evaluationcase.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case evaluationcase.FieldDatasetVersionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field dataset_version_id", values[i])
			} else if value != nil {
				_m.DatasetVersionID = *value
			}
		case evaluationcase.FieldCaseKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field case_key", values[i])
			} else if value.Valid {
				_m.CaseKey = value.String
			}
		case evaluationcase.FieldCapabilityDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capability_domain", values[i])
			} else if value.Valid {
				_m.CapabilityDomain = value.String
			}
		case evaluationcase.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case evaluationcase.FieldWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = value.Float64
			}
		case evaluationcase.FieldSampleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sample_count", values[i])
			} else if value.Valid {
				_m.SampleCount = int(value.Int64)
			}
		case evaluationcase.FieldPromptSpec:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_spec", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PromptSpec); err != nil {
					return fmt.Errorf("unmarshal field prompt_spec: %w", err)
				}
			}
		case evaluationcase.FieldExpectedSpec:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field expected_spec", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExpectedSpec); err != nil {
					return fmt.Errorf("unmarshal field expected_spec: %w", err)
				}
			}
		case evaluationcase.FieldEncryptedSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_spec", values[i])
			} else if value.Valid {
				_m.EncryptedSpec = new(string)
				*_m.EncryptedSpec = value.String
			}
		case evaluationcase.FieldExecutionSpec:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field execution_spec", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExecutionSpec); err != nil {
					return fmt.Errorf("unmarshal field execution_spec: %w", err)
				}
			}
		case evaluationcase.FieldQualityDimension:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality_dimension", values[i])
			} else if value.Valid {
				_m.QualityDimension = value.String
			}
		case evaluationcase.FieldQualityProbeSpec:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quality_probe_spec", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.QualityProbeSpec); err != nil {
					return fmt.Errorf("unmarshal field quality_probe_spec: %w", err)
				}
			}
		case evaluationcase.FieldGraderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grader_id", values[i])
			} else if value.Valid {
				_m.GraderID = value.String
			}
		case evaluationcase.FieldGraderVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grader_version", values[i])
			} else if value.Valid {
				_m.GraderVersion = value.String
			}
		case evaluationcase.FieldContentSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_sha256", values[i])
			} else if value.Valid {
				_m.ContentSha256 = value.String
			}
		case evaluationcase.FieldConfidentiality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confidentiality", values[i])
			} else if value.Valid {
				_m.Confidentiality = value.String
			}
		case evaluationcase.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case evaluationcase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EvaluationCase.
// This includes values selected through modifiers, order, etc.
func (_m *EvaluationCase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDatasetVersion queries the "dataset_version" edge of the EvaluationCase entity.
func (_m *EvaluationCase) QueryDatasetVersion() *EvaluationDatasetVersionQuery {
	return NewEvaluationCaseClient(_m.config).QueryDatasetVersion(_m)
}

// Update returns a builder for updating this EvaluationCase.
// Note that you need to call EvaluationCase.Unwrap() before calling this method if this EvaluationCase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EvaluationCase) Update() *EvaluationCaseUpdateOne {
	return NewEvaluationCaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EvaluationCase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EvaluationCase) Unwrap() *EvaluationCase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EvaluationCase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EvaluationCase) String() string {
	var builder strings.Builder
	builder.WriteString("EvaluationCase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("dataset_version_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DatasetVersionID))
	builder.WriteString(", ")
	builder.WriteString("case_key=")
	builder.WriteString(_m.CaseKey)
	builder.WriteString(", ")
	builder.WriteString("capability_domain=")
	builder.WriteString(_m.CapabilityDomain)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("sample_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SampleCount))
	builder.WriteString(", ")
	builder.WriteString("prompt_spec=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptSpec))
	builder.WriteString(", ")
	builder.WriteString("expected_spec=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedSpec))
	builder.WriteString(", ")
	if v := _m.EncryptedSpec; v != nil {
		builder.WriteString("encrypted_spec=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("execution_spec=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionSpec))
	builder.WriteString(", ")
	builder.WriteString("quality_dimension=")
	builder.WriteString(_m.QualityDimension)
	builder.WriteString(", ")
	builder.WriteString("quality_probe_spec=")
	builder.WriteString(fmt.Sprintf("%v", _m.QualityProbeSpec))
	builder.WriteString(", ")
	builder.WriteString("grader_id=")
	builder.WriteString(_m.GraderID)
	builder.WriteString(", ")
	builder.WriteString("grader_version=")
	builder.WriteString(_m.GraderVersion)
	builder.WriteString(", ")
	builder.WriteString("content_sha256=")
	builder.WriteString(_m.ContentSha256)
	builder.WriteString(", ")
	builder.WriteString("confidentiality=")
	builder.WriteString(_m.Confidentiality)
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EvaluationCases is a parsable slice of EvaluationCase.
type EvaluationCases []*EvaluationCase
