// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/evaluationdatasetversion"
	"github.com/google/uuid"
)

// EvaluationDatasetVersion is the model entity for the EvaluationDatasetVersion schema.
type EvaluationDatasetVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DatasetKey holds the value of the "dataset_key" field.
	DatasetKey string `json:"dataset_key,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// ManifestSha256 holds the value of the "manifest_sha256" field.
	ManifestSha256 string `json:"manifest_sha256,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// RetiredAt holds the value of the "retired_at" field.
	RetiredAt *time.Time `json:"retired_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EvaluationDatasetVersionQuery when eager-loading is set.
	Edges        EvaluationDatasetVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EvaluationDatasetVersionEdges holds the relations/edges for other nodes in the graph.
type EvaluationDatasetVersionEdges struct {
	// Cases holds the value of the cases edge.
	Cases []*EvaluationCase `json:"cases,omitempty"`
	// Plans holds the value of the plans edge.
	Plans []*EvaluationPlan `json:"plans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CasesOrErr returns the Cases value or an error if the edge
// was not loaded in eager-loading.
func (e EvaluationDatasetVersionEdges) CasesOrErr() ([]*EvaluationCase, error) {
	if e.loadedTypes[0] {
		return e.Cases, nil
	}
	return nil, &NotLoadedError{edge: "cases"}
}

// PlansOrErr returns the Plans value or an error if the edge
// was not loaded in eager-loading.
func (e EvaluationDatasetVersionEdges) PlansOrErr() ([]*EvaluationPlan, error) {
	if e.loadedTypes[1] {
		return e.Plans, nil
	}
	return nil, &NotLoadedError{edge: "plans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EvaluationDatasetVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case evaluationdatasetversion.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case evaluationdatasetversion.FieldDatasetKey, evaluationdatasetversion.FieldVersion, evaluationdatasetversion.FieldManifestSha256, evaluationdatasetversion.FieldSourceType, evaluationdatasetversion.FieldStatus:
			values[i] = new(sql.NullString)
		case evaluationdatasetversion.FieldPublishedAt, evaluationdatasetversion.FieldRetiredAt, evaluationdatasetversion.FieldCreatedAt, evaluationdatasetversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case evaluationdatasetversion.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EvaluationDatasetVersion fields.
func (_m *EvaluationDatasetVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case evaluationdatasetversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case evaluationdatasetversion.FieldDatasetKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dataset_key", values[i])
			} else if value.Valid {
				_m.DatasetKey = value.String
			}
		case evaluationdatasetversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case evaluationdatasetversion.FieldManifestSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_sha256", values[i])
			} else if value.Valid {
				_m.ManifestSha256 = value.String
			}
		case evaluationdatasetversion.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case evaluationdatasetversion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case evaluationdatasetversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case evaluationdatasetversion.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case evaluationdatasetversion.FieldRetiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retired_at", values[i])
			} else if value.Valid {
				_m.RetiredAt = new(time.Time)
				*_m.RetiredAt = value.Time
			}
		case evaluationdatasetversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case evaluationdatasetversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EvaluationDatasetVersion.
// This includes values selected through modifiers, order, etc.
func (_m *EvaluationDatasetVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCases queries the "cases" edge of the EvaluationDatasetVersion entity.
func (_m *EvaluationDatasetVersion) QueryCases() *EvaluationCaseQuery {
	return NewEvaluationDatasetVersionClient(_m.config).QueryCases(_m)
}

// QueryPlans queries the "plans" edge of the EvaluationDatasetVersion entity.
func (_m *EvaluationDatasetVersion) QueryPlans() *EvaluationPlanQuery {
	return NewEvaluationDatasetVersionClient(_m.config).QueryPlans(_m)
}

// Update returns a builder for updating this EvaluationDatasetVersion.
// Note that you need to call EvaluationDatasetVersion.Unwrap() before calling this method if this EvaluationDatasetVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EvaluationDatasetVersion) Update() *EvaluationDatasetVersionUpdateOne {
	return NewEvaluationDatasetVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EvaluationDatasetVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EvaluationDatasetVersion) Unwrap() *EvaluationDatasetVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EvaluationDatasetVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EvaluationDatasetVersion) String() string {
	var builder strings.Builder
	builder.WriteString("EvaluationDatasetVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("dataset_key=")
	builder.WriteString(_m.DatasetKey)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("manifest_sha256=")
	builder.WriteString(_m.ManifestSha256)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RetiredAt; v != nil {
		builder.WriteString("retired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EvaluationDatasetVersions is a parsable slice of EvaluationDatasetVersion.
type EvaluationDatasetVersions []*EvaluationDatasetVersion
