// Code generated by ent, DO NOT EDIT.

package evaluationdatasetversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldID, id))
}

// DatasetKey applies equality check predicate on the "dataset_key" field. It's identical to DatasetKeyEQ.
func DatasetKey(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldDatasetKey, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldVersion, v))
}

// ManifestSha256 applies equality check predicate on the "manifest_sha256" field. It's identical to ManifestSha256EQ.
func ManifestSha256(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldManifestSha256, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldSourceType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// RetiredAt applies equality check predicate on the "retired_at" field. It's identical to RetiredAtEQ.
func RetiredAt(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldRetiredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// DatasetKeyEQ applies the EQ predicate on the "dataset_key" field.
func DatasetKeyEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldDatasetKey, v))
}

// DatasetKeyNEQ applies the NEQ predicate on the "dataset_key" field.
func DatasetKeyNEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldDatasetKey, v))
}

// DatasetKeyIn applies the In predicate on the "dataset_key" field.
func DatasetKeyIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldDatasetKey, vs...))
}

// DatasetKeyNotIn applies the NotIn predicate on the "dataset_key" field.
func DatasetKeyNotIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldDatasetKey, vs...))
}

// DatasetKeyGT applies the GT predicate on the "dataset_key" field.
func DatasetKeyGT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldDatasetKey, v))
}

// DatasetKeyGTE applies the GTE predicate on the "dataset_key" field.
func DatasetKeyGTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldDatasetKey, v))
}

// DatasetKeyLT applies the LT predicate on the "dataset_key" field.
func DatasetKeyLT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldDatasetKey, v))
}

// DatasetKeyLTE applies the LTE predicate on the "dataset_key" field.
func DatasetKeyLTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldDatasetKey, v))
}

// DatasetKeyContains applies the Contains predicate on the "dataset_key" field.
func DatasetKeyContains(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContains(FieldDatasetKey, v))
}

// DatasetKeyHasPrefix applies the HasPrefix predicate on the "dataset_key" field.
func DatasetKeyHasPrefix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasPrefix(FieldDatasetKey, v))
}

// DatasetKeyHasSuffix applies the HasSuffix predicate on the "dataset_key" field.
func DatasetKeyHasSuffix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasSuffix(FieldDatasetKey, v))
}

// DatasetKeyEqualFold applies the EqualFold predicate on the "dataset_key" field.
func DatasetKeyEqualFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEqualFold(FieldDatasetKey, v))
}

// DatasetKeyContainsFold applies the ContainsFold predicate on the "dataset_key" field.
func DatasetKeyContainsFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContainsFold(FieldDatasetKey, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContainsFold(FieldVersion, v))
}

// ManifestSha256EQ applies the EQ predicate on the "manifest_sha256" field.
func ManifestSha256EQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldManifestSha256, v))
}

// ManifestSha256NEQ applies the NEQ predicate on the "manifest_sha256" field.
func ManifestSha256NEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldManifestSha256, v))
}

// ManifestSha256In applies the In predicate on the "manifest_sha256" field.
func ManifestSha256In(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldManifestSha256, vs...))
}

// ManifestSha256NotIn applies the NotIn predicate on the "manifest_sha256" field.
func ManifestSha256NotIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldManifestSha256, vs...))
}

// ManifestSha256GT applies the GT predicate on the "manifest_sha256" field.
func ManifestSha256GT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldManifestSha256, v))
}

// ManifestSha256GTE applies the GTE predicate on the "manifest_sha256" field.
func ManifestSha256GTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldManifestSha256, v))
}

// ManifestSha256LT applies the LT predicate on the "manifest_sha256" field.
func ManifestSha256LT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldManifestSha256, v))
}

// ManifestSha256LTE applies the LTE predicate on the "manifest_sha256" field.
func ManifestSha256LTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldManifestSha256, v))
}

// ManifestSha256Contains applies the Contains predicate on the "manifest_sha256" field.
func ManifestSha256Contains(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContains(FieldManifestSha256, v))
}

// ManifestSha256HasPrefix applies the HasPrefix predicate on the "manifest_sha256" field.
func ManifestSha256HasPrefix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasPrefix(FieldManifestSha256, v))
}

// ManifestSha256HasSuffix applies the HasSuffix predicate on the "manifest_sha256" field.
func ManifestSha256HasSuffix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasSuffix(FieldManifestSha256, v))
}

// ManifestSha256EqualFold applies the EqualFold predicate on the "manifest_sha256" field.
func ManifestSha256EqualFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEqualFold(FieldManifestSha256, v))
}

// ManifestSha256ContainsFold applies the ContainsFold predicate on the "manifest_sha256" field.
func ManifestSha256ContainsFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContainsFold(FieldManifestSha256, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContainsFold(FieldSourceType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldCreatedBy, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotNull(FieldPublishedAt))
}

// RetiredAtEQ applies the EQ predicate on the "retired_at" field.
func RetiredAtEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldRetiredAt, v))
}

// RetiredAtNEQ applies the NEQ predicate on the "retired_at" field.
func RetiredAtNEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldRetiredAt, v))
}

// RetiredAtIn applies the In predicate on the "retired_at" field.
func RetiredAtIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldRetiredAt, vs...))
}

// RetiredAtNotIn applies the NotIn predicate on the "retired_at" field.
func RetiredAtNotIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldRetiredAt, vs...))
}

// RetiredAtGT applies the GT predicate on the "retired_at" field.
func RetiredAtGT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldRetiredAt, v))
}

// RetiredAtGTE applies the GTE predicate on the "retired_at" field.
func RetiredAtGTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldRetiredAt, v))
}

// RetiredAtLT applies the LT predicate on the "retired_at" field.
func RetiredAtLT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldRetiredAt, v))
}

// RetiredAtLTE applies the LTE predicate on the "retired_at" field.
func RetiredAtLTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldRetiredAt, v))
}

// RetiredAtIsNil applies the IsNil predicate on the "retired_at" field.
func RetiredAtIsNil() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIsNull(FieldRetiredAt))
}

// RetiredAtNotNil applies the NotNil predicate on the "retired_at" field.
func RetiredAtNotNil() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotNull(FieldRetiredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCases applies the HasEdge predicate on the "cases" edge.
func HasCases() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CasesTable, CasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCasesWith applies the HasEdge predicate on the "cases" edge with a given conditions (other predicates).
func HasCasesWith(preds ...predicate.EvaluationCase) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(func(s *sql.Selector) {
		step := newCasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlans applies the HasEdge predicate on the "plans" edge.
func HasPlans() predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlansTable, PlansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlansWith applies the HasEdge predicate on the "plans" edge with a given conditions (other predicates).
func HasPlansWith(preds ...predicate.EvaluationPlan) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(func(s *sql.Selector) {
		step := newPlansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EvaluationDatasetVersion) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EvaluationDatasetVersion) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EvaluationDatasetVersion) predicate.EvaluationDatasetVersion {
	return predicate.EvaluationDatasetVersion(sql.NotPredicates(p))
}
