// Code generated by ent, DO NOT EDIT.

package evaluationrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the evaluationrun type in the database.
	Label = "evaluation_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldTriggerSource holds the string denoting the trigger_source field in the database.
	FieldTriggerSource = "trigger_source"
	// FieldBaselineRef holds the string denoting the baseline_ref field in the database.
	FieldBaselineRef = "baseline_ref"
	// FieldCandidateRef holds the string denoting the candidate_ref field in the database.
	FieldCandidateRef = "candidate_ref"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBudgetLimit holds the string denoting the budget_limit field in the database.
	FieldBudgetLimit = "budget_limit"
	// FieldReservedCost holds the string denoting the reserved_cost field in the database.
	FieldReservedCost = "reserved_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldCalibrationMode holds the string denoting the calibration_mode field in the database.
	FieldCalibrationMode = "calibration_mode"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// Table holds the table name of the evaluationrun in the database.
	Table = "evaluation_runs"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "evaluation_runs"
	// PlanInverseTable is the table name for the EvaluationPlan entity.
	// It exists in this package in order to avoid circular dependency with the "evaluationplan" package.
	PlanInverseTable = "evaluation_plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_id"
)

// Columns holds all SQL columns for evaluationrun fields.
var Columns = []string{
	FieldID,
	FieldPlanID,
	FieldTriggerSource,
	FieldBaselineRef,
	FieldCandidateRef,
	FieldStatus,
	FieldBudgetLimit,
	FieldReservedCost,
	FieldActualCost,
	FieldCalibrationMode,
	FieldCreatedBy,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TriggerSourceValidator is a validator for the "trigger_source" field. It is called by the builders before save.
	TriggerSourceValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultReservedCost holds the default value on creation for the "reserved_cost" field.
	DefaultReservedCost float64
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// DefaultCalibrationMode holds the default value on creation for the "calibration_mode" field.
	DefaultCalibrationMode bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EvaluationRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByTriggerSource orders the results by the trigger_source field.
func ByTriggerSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBudgetLimit orders the results by the budget_limit field.
func ByBudgetLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetLimit, opts...).ToFunc()
}

// ByReservedCost orders the results by the reserved_cost field.
func ByReservedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByCalibrationMode orders the results by the calibration_mode field.
func ByCalibrationMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalibrationMode, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
