// Code generated by ent, DO NOT EDIT.

package evaluationrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldID, id))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldPlanID, v))
}

// TriggerSource applies equality check predicate on the "trigger_source" field. It's identical to TriggerSourceEQ.
func TriggerSource(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldTriggerSource, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldStatus, v))
}

// BudgetLimit applies equality check predicate on the "budget_limit" field. It's identical to BudgetLimitEQ.
func BudgetLimit(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldBudgetLimit, v))
}

// ReservedCost applies equality check predicate on the "reserved_cost" field. It's identical to ReservedCostEQ.
func ReservedCost(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldReservedCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldActualCost, v))
}

// CalibrationMode applies equality check predicate on the "calibration_mode" field. It's identical to CalibrationModeEQ.
func CalibrationMode(v bool) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCalibrationMode, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCreatedBy, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...uuid.UUID) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldPlanID, vs...))
}

// TriggerSourceEQ applies the EQ predicate on the "trigger_source" field.
func TriggerSourceEQ(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldTriggerSource, v))
}

// TriggerSourceNEQ applies the NEQ predicate on the "trigger_source" field.
func TriggerSourceNEQ(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldTriggerSource, v))
}

// TriggerSourceIn applies the In predicate on the "trigger_source" field.
func TriggerSourceIn(vs ...string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldTriggerSource, vs...))
}

// TriggerSourceNotIn applies the NotIn predicate on the "trigger_source" field.
func TriggerSourceNotIn(vs ...string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldTriggerSource, vs...))
}

// TriggerSourceGT applies the GT predicate on the "trigger_source" field.
func TriggerSourceGT(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldTriggerSource, v))
}

// TriggerSourceGTE applies the GTE predicate on the "trigger_source" field.
func TriggerSourceGTE(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldTriggerSource, v))
}

// TriggerSourceLT applies the LT predicate on the "trigger_source" field.
func TriggerSourceLT(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldTriggerSource, v))
}

// TriggerSourceLTE applies the LTE predicate on the "trigger_source" field.
func TriggerSourceLTE(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldTriggerSource, v))
}

// TriggerSourceContains applies the Contains predicate on the "trigger_source" field.
func TriggerSourceContains(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldContains(FieldTriggerSource, v))
}

// TriggerSourceHasPrefix applies the HasPrefix predicate on the "trigger_source" field.
func TriggerSourceHasPrefix(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldHasPrefix(FieldTriggerSource, v))
}

// TriggerSourceHasSuffix applies the HasSuffix predicate on the "trigger_source" field.
func TriggerSourceHasSuffix(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldHasSuffix(FieldTriggerSource, v))
}

// TriggerSourceEqualFold applies the EqualFold predicate on the "trigger_source" field.
func TriggerSourceEqualFold(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEqualFold(FieldTriggerSource, v))
}

// TriggerSourceContainsFold applies the ContainsFold predicate on the "trigger_source" field.
func TriggerSourceContainsFold(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldContainsFold(FieldTriggerSource, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldContainsFold(FieldStatus, v))
}

// BudgetLimitEQ applies the EQ predicate on the "budget_limit" field.
func BudgetLimitEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldBudgetLimit, v))
}

// BudgetLimitNEQ applies the NEQ predicate on the "budget_limit" field.
func BudgetLimitNEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldBudgetLimit, v))
}

// BudgetLimitIn applies the In predicate on the "budget_limit" field.
func BudgetLimitIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldBudgetLimit, vs...))
}

// BudgetLimitNotIn applies the NotIn predicate on the "budget_limit" field.
func BudgetLimitNotIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldBudgetLimit, vs...))
}

// BudgetLimitGT applies the GT predicate on the "budget_limit" field.
func BudgetLimitGT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldBudgetLimit, v))
}

// BudgetLimitGTE applies the GTE predicate on the "budget_limit" field.
func BudgetLimitGTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldBudgetLimit, v))
}

// BudgetLimitLT applies the LT predicate on the "budget_limit" field.
func BudgetLimitLT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldBudgetLimit, v))
}

// BudgetLimitLTE applies the LTE predicate on the "budget_limit" field.
func BudgetLimitLTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldBudgetLimit, v))
}

// ReservedCostEQ applies the EQ predicate on the "reserved_cost" field.
func ReservedCostEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldReservedCost, v))
}

// ReservedCostNEQ applies the NEQ predicate on the "reserved_cost" field.
func ReservedCostNEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldReservedCost, v))
}

// ReservedCostIn applies the In predicate on the "reserved_cost" field.
func ReservedCostIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldReservedCost, vs...))
}

// ReservedCostNotIn applies the NotIn predicate on the "reserved_cost" field.
func ReservedCostNotIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldReservedCost, vs...))
}

// ReservedCostGT applies the GT predicate on the "reserved_cost" field.
func ReservedCostGT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldReservedCost, v))
}

// ReservedCostGTE applies the GTE predicate on the "reserved_cost" field.
func ReservedCostGTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldReservedCost, v))
}

// ReservedCostLT applies the LT predicate on the "reserved_cost" field.
func ReservedCostLT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldReservedCost, v))
}

// ReservedCostLTE applies the LTE predicate on the "reserved_cost" field.
func ReservedCostLTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldReservedCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldActualCost, v))
}

// CalibrationModeEQ applies the EQ predicate on the "calibration_mode" field.
func CalibrationModeEQ(v bool) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCalibrationMode, v))
}

// CalibrationModeNEQ applies the NEQ predicate on the "calibration_mode" field.
func CalibrationModeNEQ(v bool) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldCalibrationMode, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotNull(FieldCreatedBy))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.EvaluationRun {
	return predicate.EvaluationRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.EvaluationPlan) predicate.EvaluationRun {
	return predicate.EvaluationRun(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EvaluationRun) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EvaluationRun) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EvaluationRun) predicate.EvaluationRun {
	return predicate.EvaluationRun(sql.NotPredicates(p))
}
